from .monedas_dto import (
    MonedaBase,
    MonedaCreate,
    MonedaRead,
    MonedaUpdate,
)
from .categorias_dto import (
    CategoriasBase,
    CategoriasCreate,
    CategoriasRead,
    CategoriasUpdate,
    SubcategoriasBase,
    SubcategoriasCreate,
    SubcategoriasRead,
    SubcategoriasUpdate,
)
from .productos_dto import (
    ProductosBase,
    ProductosCreate,
    ProductosRead,
    ProductosUpdate,
    ProductoSimpleRead,
)
from .ventas_dto import (
    DetalleVentaBase,
    DetalleVentaCreate,
    DetalleVentaRead,
    VentaBase,
    VentaCreate,
    VentaRead,
    VentaUpdate,
)
from .clientes_dto import (
    ClienteBase,
    ClienteCreate,
    ClienteRead,
    ClienteReadWithVentas,
    ClienteUpdate,
)
from .movimientos_dto import (
    TipoMovimientoBase,
    TipoMovimientoCreate,
    TipoMovimientoRead,
    TipoMovimientoUpdate,
    MovimientoBase,
    MovimientoCreate,
    MovimientoRead,
    MovimientoUpdate,
)
from .dependencias_dto import DependenciaRead
from .dashboard_dto import DashboardStats

__all__ = [
    "MonedaBase",
    "MonedaCreate",
    "MonedaRead",
    "MonedaUpdate",
    "CategoriasBase",
    "CategoriasCreate",
    "CategoriasRead",
    "CategoriasUpdate",
    "SubcategoriasBase",
    "SubcategoriasCreate",
    "SubcategoriasRead",
    "SubcategoriasUpdate",
    "ProductosBase",
    "ProductosCreate",
    "ProductosRead",
    "ProductosUpdate",
    "ProductoSimpleRead",
    "DetalleVentaBase",
    "DetalleVentaCreate",
    "DetalleVentaRead",
    "VentaBase",
    "VentaCreate",
    "VentaRead",
    "VentaUpdate",
    "ClienteBase",
    "ClienteCreate",
    "ClienteRead",
    "ClienteReadWithVentas",
    "ClienteUpdate",
    "TipoMovimientoBase",
    "TipoMovimientoCreate",
    "TipoMovimientoRead",
    "TipoMovimientoUpdate",
    "MovimientoBase",
    "MovimientoCreate",
    "MovimientoRead",
    "MovimientoUpdate",
    "DependenciaRead",
    "DashboardStats",
]
