"""Add contracts tables

Revision ID: 26bae45686ea
Revises:
Create Date: 2026-03-09 12:41:08.199403

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "26bae45686ea"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tipo_cliente",
        sa.Column("id_tipo_cliente", sa.Integer(), nullable=False),
        sa.Column(
            "nombre", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("descripcion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id_tipo_cliente"),
    )
    op.create_table(
        "tipo_entidad",
        sa.Column("id_tipo_entidad", sa.Integer(), nullable=False),
        sa.Column(
            "nombre", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("descripcion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id_tipo_entidad"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_table(
        "cliente_tcp",
        sa.Column("id_cliente", sa.Integer(), nullable=False),
        sa.Column(
            "nombre", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "primer_apellido",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
        ),
        sa.Column(
            "segundo_apellido",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=True,
        ),
        sa.Column("direccion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "numero_registro_proyecto",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=True,
        ),
        sa.Column("fecha_aprobacion", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_cliente"],
            ["clientes.id_cliente"],
        ),
        sa.PrimaryKeyConstraint("id_cliente"),
    )
    op.create_table(
        "clientes_persona_juridica",
        sa.Column("id_cliente", sa.Integer(), nullable=False),
        sa.Column(
            "codigo_reup", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("id_tipo_entidad", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_cliente"],
            ["clientes.id_cliente"],
        ),
        sa.ForeignKeyConstraint(
            ["id_tipo_entidad"],
            ["tipo_entidad.id_tipo_entidad"],
        ),
        sa.PrimaryKeyConstraint("id_cliente"),
        sa.UniqueConstraint("codigo_reup"),
    )
    op.create_table(
        "clientes_persona_natural",
        sa.Column("id_cliente", sa.Integer(), nullable=False),
        sa.Column(
            "nombre", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "primer_apellido",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
        ),
        sa.Column(
            "segundo_apellido",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=True,
        ),
        sa.Column(
            "carnet_identidad",
            sqlmodel.sql.sqltypes.AutoString(length=11),
            nullable=False,
        ),
        sa.Column(
            "codigo_expediente",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=True,
        ),
        sa.Column(
            "numero_registro",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=True,
        ),
        sa.Column(
            "catalogo", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("es_trabajador", sa.Boolean(), nullable=False),
        sa.Column(
            "ocupacion", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column(
            "centro_trabajo",
            sqlmodel.sql.sqltypes.AutoString(length=200),
            nullable=True,
        ),
        sa.Column(
            "correo_trabajo",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
        sa.Column(
            "direccion_trabajo", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "telefono_trabajo",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=True,
        ),
        sa.Column("en_baja", sa.Boolean(), nullable=False),
        sa.Column("fecha_baja", sa.Date(), nullable=True),
        sa.Column("vigencia", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_cliente"],
            ["clientes.id_cliente"],
        ),
        sa.PrimaryKeyConstraint("id_cliente"),
        sa.UniqueConstraint("carnet_identidad"),
    )
    op.create_table(
        "contrato",
        sa.Column("id_contrato", sa.Integer(), nullable=False),
        sa.Column("id_cliente", sa.Integer(), nullable=False),
        sa.Column(
            "nombre", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column(
            "proforma", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("id_estado", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("vigencia", sa.Date(), nullable=False),
        sa.Column("id_tipo_contrato", sa.Integer(), nullable=False),
        sa.Column("id_moneda", sa.Integer(), nullable=False),
        sa.Column("monto", sa.Numeric(), nullable=False),
        sa.Column(
            "documento_final",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id_cliente"],
            ["clientes.id_cliente"],
        ),
        sa.ForeignKeyConstraint(
            ["id_estado"],
            ["estado_contrato.id_estado_contrato"],
        ),
        sa.ForeignKeyConstraint(
            ["id_moneda"],
            ["moneda.id_moneda"],
        ),
        sa.ForeignKeyConstraint(
            ["id_tipo_contrato"],
            ["tipo_contrato.id_tipo_contrato"],
        ),
        sa.PrimaryKeyConstraint("id_contrato"),
    )
    op.create_table(
        "venta_efectivo",
        sa.Column("id_venta_efectivo", sa.Integer(), nullable=False),
        sa.Column("slip", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("id_dependencia", sa.Integer(), nullable=False),
        sa.Column(
            "cajero", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("monto", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_dependencia"],
            ["dependencia.id_dependencia"],
        ),
        sa.PrimaryKeyConstraint("id_venta_efectivo"),
    )
    op.create_table(
        "contrato_producto",
        sa.Column("id_contrato_producto", sa.Integer(), nullable=False),
        sa.Column("id_contrato", sa.Integer(), nullable=False),
        sa.Column("id_producto", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_contrato"],
            ["contrato.id_contrato"],
        ),
        sa.ForeignKeyConstraint(
            ["id_producto"],
            ["productos.id_producto"],
        ),
        sa.PrimaryKeyConstraint("id_contrato_producto"),
    )
    op.create_table(
        "factura",
        sa.Column("id_factura", sa.Integer(), nullable=False),
        sa.Column("id_contrato", sa.Integer(), nullable=False),
        sa.Column(
            "codigo_factura",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
        ),
        sa.Column("descripcion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("observaciones", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("monto", sa.Numeric(), nullable=False),
        sa.Column("pago_actual", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_contrato"],
            ["contrato.id_contrato"],
        ),
        sa.PrimaryKeyConstraint("id_factura"),
        sa.UniqueConstraint("codigo_factura"),
    )
    op.create_table(
        "suplemento",
        sa.Column("id_suplemento", sa.Integer(), nullable=False),
        sa.Column("id_contrato", sa.Integer(), nullable=False),
        sa.Column(
            "nombre", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column("id_estado", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("monto", sa.Numeric(), nullable=False),
        sa.Column(
            "documento", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["id_contrato"],
            ["contrato.id_contrato"],
        ),
        sa.ForeignKeyConstraint(
            ["id_estado"],
            ["estado_contrato.id_estado_contrato"],
        ),
        sa.PrimaryKeyConstraint("id_suplemento"),
    )
    op.create_table(
        "venta_efectivo_producto",
        sa.Column("id_venta_efectivo_producto", sa.Integer(), nullable=False),
        sa.Column("id_venta_efectivo", sa.Integer(), nullable=False),
        sa.Column("id_producto", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_producto"],
            ["productos.id_producto"],
        ),
        sa.ForeignKeyConstraint(
            ["id_venta_efectivo"],
            ["venta_efectivo.id_venta_efectivo"],
        ),
        sa.PrimaryKeyConstraint("id_venta_efectivo_producto"),
    )
    op.create_table(
        "anexo_producto",
        sa.Column("id_anexo_producto", sa.Integer(), nullable=False),
        sa.Column("id_anexo", sa.Integer(), nullable=False),
        sa.Column("id_producto", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("precio_compra", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_anexo"],
            ["anexo.id_anexo"],
        ),
        sa.ForeignKeyConstraint(
            ["id_producto"],
            ["productos.id_producto"],
        ),
        sa.PrimaryKeyConstraint("id_anexo_producto"),
    )
    op.create_table(
        "factura_producto",
        sa.Column("id_factura_producto", sa.Integer(), nullable=False),
        sa.Column("id_factura", sa.Integer(), nullable=False),
        sa.Column("id_producto", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_factura"],
            ["factura.id_factura"],
        ),
        sa.ForeignKeyConstraint(
            ["id_producto"],
            ["productos.id_producto"],
        ),
        sa.PrimaryKeyConstraint("id_factura_producto"),
    )
    op.create_table(
        "suplemento_producto",
        sa.Column("id_suplemento_producto", sa.Integer(), nullable=False),
        sa.Column("id_suplemento", sa.Integer(), nullable=False),
        sa.Column("id_producto", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_producto"],
            ["productos.id_producto"],
        ),
        sa.ForeignKeyConstraint(
            ["id_suplemento"],
            ["suplemento.id_suplemento"],
        ),
        sa.PrimaryKeyConstraint("id_suplemento_producto"),
    )
    op.drop_table("tipo_provedores")
    op.drop_table("conexion_database")
    op.drop_table("provedores")
    op.drop_table("sesion")
    op.drop_table("datos_generales_dependencia")
    op.add_column("anexo", sa.Column("id_moneda", sa.Integer(), nullable=True))
    op.add_column(
        "anexo",
        sa.Column(
            "codigo_anexo", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
    )
    op.alter_column(
        "anexo", "id_dependencia", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_index(op.f("idx_anexo_convenio"), table_name="anexo")
    op.drop_index(op.f("idx_anexo_dependencia"), table_name="anexo")
    op.drop_index(op.f("idx_anexo_numero"), table_name="anexo")
    op.drop_index(op.f("idx_anexo_producto"), table_name="anexo")
    op.drop_constraint(op.f("fk_anexo_producto"), "anexo", type_="foreignkey")
    op.create_foreign_key(None, "anexo", "moneda", ["id_moneda"], ["id_moneda"])
    op.drop_column("anexo", "id_producto")
    op.drop_column("anexo", "numero_anexo")
    op.add_column(
        "clientes",
        sa.Column(
            "numero_cliente",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=False,
        ),
    )
    op.add_column(
        "clientes", sa.Column("tipo_persona", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "clientes",
        sa.Column("fax", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    )
    op.add_column(
        "clientes",
        sa.Column("web", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    )
    op.add_column("clientes", sa.Column("id_provincia", sa.Integer(), nullable=True))
    op.add_column("clientes", sa.Column("id_municipio", sa.Integer(), nullable=True))
    op.add_column(
        "clientes",
        sa.Column(
            "codigo_postal", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True
        ),
    )
    op.add_column(
        "clientes",
        sa.Column(
            "tipo_relacion", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
    )
    op.add_column(
        "clientes",
        sa.Column(
            "estado", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
    )
    op.alter_column(
        "clientes",
        "nombre",
        existing_type=sa.VARCHAR(length=150),
        type_=sqlmodel.sql.sqltypes.AutoString(length=200),
        existing_nullable=False,
    )
    op.alter_column(
        "clientes", "cedula_rif", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.alter_column(
        "clientes",
        "fecha_registro",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Date(),
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_clientes_cedula"), table_name="clientes")
    op.create_unique_constraint(None, "clientes", ["cedula_rif"])
    op.create_foreign_key(
        None, "clientes", "municipio", ["id_municipio"], ["id_municipio"]
    )
    op.create_foreign_key(
        None, "clientes", "provincia", ["id_provincia"], ["id_provincia"]
    )
    op.add_column(
        "convenio",
        sa.Column(
            "codigo_convenio",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=True,
        ),
    )
    op.add_column("convenio", sa.Column("id_cliente", sa.Integer(), nullable=False))
    op.drop_index(op.f("idx_convenio_provedor"), table_name="convenio")
    op.drop_constraint(
        op.f("convenio_id_provedor_fkey"), "convenio", type_="foreignkey"
    )
    op.create_foreign_key(None, "convenio", "clientes", ["id_cliente"], ["id_cliente"])
    op.drop_column("convenio", "id_provedor")
    op.add_column("cuenta", sa.Column("id_cliente", sa.Integer(), nullable=True))
    op.add_column(
        "cuenta",
        sa.Column(
            "numero_cuenta", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
    )
    op.drop_index(op.f("idx_cuenta_dependencia"), table_name="cuenta")
    op.drop_index(op.f("idx_cuenta_tipo_cuenta"), table_name="cuenta")
    op.create_foreign_key(None, "cuenta", "clientes", ["id_cliente"], ["id_cliente"])
    op.alter_column(
        "dependencia", "direccion", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "dependencia", "telefono", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.alter_column(
        "dependencia",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_dependencia_tipo"), table_name="dependencia")
    op.drop_constraint(
        op.f("dependencia_id_municipio_fkey"), "dependencia", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_dependencia_conexion"), "dependencia", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("dependencia_codigo_padre_fkey"), "dependencia", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("dependencia_id_provincia_fkey"), "dependencia", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "dependencia", "provincia", ["id_provincia"], ["id_provincia"]
    )
    op.create_foreign_key(
        None, "dependencia", "dependencia", ["codigo_padre"], ["id_dependencia"]
    )
    op.create_foreign_key(
        None, "dependencia", "municipio", ["id_municipio"], ["id_municipio"]
    )
    op.drop_column("dependencia", "usuario")
    op.drop_column("dependencia", "contrasenia")
    op.drop_column("dependencia", "base_datos")
    op.drop_column("dependencia", "puerto")
    op.drop_column("dependencia", "id_conexion")
    op.drop_column("dependencia", "host")
    op.drop_index(op.f("idx_detalle_venta_producto"), table_name="detalle_ventas")
    op.drop_index(op.f("idx_detalle_venta_venta"), table_name="detalle_ventas")
    op.alter_column(
        "estado_contrato",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "grupo",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("grupo_funcionalidad_id_grupo_fkey"),
        "grupo_funcionalidad",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("grupo_funcionalidad_id_funcionalidad_fkey"),
        "grupo_funcionalidad",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "grupo_funcionalidad", "grupo", ["id_grupo"], ["id_grupo"]
    )
    op.create_foreign_key(
        None,
        "grupo_funcionalidad",
        "funcionalidad",
        ["id_funcionalidad"],
        ["id_funcionalidad"],
    )
    op.add_column("movimiento", sa.Column("id_cliente", sa.Integer(), nullable=True))
    op.drop_index(op.f("idx_movimiento_codigo"), table_name="movimiento")
    op.drop_index(op.f("idx_movimiento_convenio"), table_name="movimiento")
    op.drop_index(op.f("idx_movimiento_dependencia"), table_name="movimiento")
    op.drop_index(op.f("idx_movimiento_estado"), table_name="movimiento")
    op.drop_index(op.f("idx_movimiento_producto"), table_name="movimiento")
    op.drop_index(op.f("idx_movimiento_provedor"), table_name="movimiento")
    op.drop_index(op.f("idx_movimiento_tipo"), table_name="movimiento")
    op.drop_index(op.f("ix_movimiento_codigo"), table_name="movimiento")
    op.drop_constraint(op.f("fk_movimiento_provedor"), "movimiento", type_="foreignkey")
    op.create_foreign_key(
        None, "movimiento", "clientes", ["id_cliente"], ["id_cliente"]
    )
    op.drop_column("movimiento", "id_provedor")
    op.drop_constraint(
        op.f("municipio_id_provincia_nombre_key"), "municipio", type_="unique"
    )
    op.drop_constraint(
        op.f("municipio_id_provincia_fkey"), "municipio", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "municipio", "provincia", ["id_provincia"], ["id_provincia"]
    )
    op.drop_index(op.f("idx_productos_codigo"), table_name="productos")
    op.drop_index(op.f("idx_productos_subcategoria"), table_name="productos")
    op.drop_index(op.f("ix_productos_codigo"), table_name="productos")
    op.create_unique_constraint(None, "productos", ["codigo"])
    op.drop_column("productos", "stock")
    op.alter_column(
        "tipo_contrato",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "tipo_convenio",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "tipo_cuenta",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_usuarios_dependencia"), table_name="usuarios")
    op.drop_index(op.f("idx_usuarios_grupo"), table_name="usuarios")
    op.drop_constraint(op.f("usuarios_id_grupo_fkey"), "usuarios", type_="foreignkey")
    op.drop_constraint(
        op.f("usuarios_id_dependencia_fkey"), "usuarios", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "usuarios", "dependencia", ["id_dependencia"], ["id_dependencia"]
    )
    op.create_foreign_key(None, "usuarios", "grupo", ["id_grupo"], ["id_grupo"])
    op.drop_index(op.f("idx_ventas_cliente"), table_name="ventas")
    op.drop_index(op.f("idx_ventas_estado"), table_name="ventas")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_ventas_estado"), "ventas", ["estado"], unique=False)
    op.create_index(op.f("idx_ventas_cliente"), "ventas", ["id_cliente"], unique=False)
    op.drop_constraint(None, "usuarios", type_="foreignkey")
    op.drop_constraint(None, "usuarios", type_="foreignkey")
    op.create_foreign_key(
        op.f("usuarios_id_dependencia_fkey"),
        "usuarios",
        "dependencia",
        ["id_dependencia"],
        ["id_dependencia"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("usuarios_id_grupo_fkey"),
        "usuarios",
        "grupo",
        ["id_grupo"],
        ["id_grupo"],
        ondelete="CASCADE",
    )
    op.create_index(op.f("idx_usuarios_grupo"), "usuarios", ["id_grupo"], unique=False)
    op.create_index(
        op.f("idx_usuarios_dependencia"), "usuarios", ["id_dependencia"], unique=False
    )
    op.alter_column(
        "tipo_cuenta",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "tipo_convenio",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "tipo_contrato",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.add_column(
        "productos",
        sa.Column(
            "stock",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "productos", type_="unique")
    op.create_index(op.f("ix_productos_codigo"), "productos", ["codigo"], unique=True)
    op.create_index(
        op.f("idx_productos_subcategoria"),
        "productos",
        ["id_subcategoria"],
        unique=False,
    )
    op.create_index(op.f("idx_productos_codigo"), "productos", ["codigo"], unique=False)
    op.drop_constraint(None, "municipio", type_="foreignkey")
    op.create_foreign_key(
        op.f("municipio_id_provincia_fkey"),
        "municipio",
        "provincia",
        ["id_provincia"],
        ["id_provincia"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        op.f("municipio_id_provincia_nombre_key"),
        "municipio",
        ["id_provincia", "nombre"],
        postgresql_nulls_not_distinct=False,
    )
    op.add_column(
        "movimiento",
        sa.Column("id_provedor", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_movimiento_provedor"),
        "movimiento",
        "provedores",
        ["id_provedor"],
        ["id_provedores"],
    )
    op.create_index(
        op.f("ix_movimiento_codigo"), "movimiento", ["codigo"], unique=False
    )
    op.create_index(
        op.f("idx_movimiento_tipo"), "movimiento", ["id_tipo_movimiento"], unique=False
    )
    op.create_index(
        op.f("idx_movimiento_provedor"), "movimiento", ["id_provedor"], unique=False
    )
    op.create_index(
        op.f("idx_movimiento_producto"), "movimiento", ["id_producto"], unique=False
    )
    op.create_index(
        op.f("idx_movimiento_estado"), "movimiento", ["estado"], unique=False
    )
    op.create_index(
        op.f("idx_movimiento_dependencia"),
        "movimiento",
        ["id_dependencia"],
        unique=False,
    )
    op.create_index(
        op.f("idx_movimiento_convenio"), "movimiento", ["id_convenio"], unique=False
    )
    op.create_index(
        op.f("idx_movimiento_codigo"), "movimiento", ["codigo"], unique=False
    )
    op.drop_column("movimiento", "id_cliente")
    op.drop_constraint(None, "grupo_funcionalidad", type_="foreignkey")
    op.drop_constraint(None, "grupo_funcionalidad", type_="foreignkey")
    op.create_foreign_key(
        op.f("grupo_funcionalidad_id_funcionalidad_fkey"),
        "grupo_funcionalidad",
        "funcionalidad",
        ["id_funcionalidad"],
        ["id_funcionalidad"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("grupo_funcionalidad_id_grupo_fkey"),
        "grupo_funcionalidad",
        "grupo",
        ["id_grupo"],
        ["id_grupo"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "grupo",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "estado_contrato",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.create_index(
        op.f("idx_detalle_venta_venta"), "detalle_ventas", ["id_venta"], unique=False
    )
    op.create_index(
        op.f("idx_detalle_venta_producto"),
        "detalle_ventas",
        ["id_producto"],
        unique=False,
    )
    op.add_column(
        "dependencia",
        sa.Column(
            "host",
            sa.VARCHAR(length=100),
            server_default=sa.text("'localhost'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "dependencia",
        sa.Column("id_conexion", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "dependencia",
        sa.Column(
            "puerto",
            sa.INTEGER(),
            server_default=sa.text("5432"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "dependencia",
        sa.Column(
            "base_datos", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "dependencia",
        sa.Column(
            "contrasenia", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "dependencia",
        sa.Column(
            "usuario", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "dependencia", type_="foreignkey")
    op.drop_constraint(None, "dependencia", type_="foreignkey")
    op.drop_constraint(None, "dependencia", type_="foreignkey")
    op.create_foreign_key(
        op.f("dependencia_id_provincia_fkey"),
        "dependencia",
        "provincia",
        ["id_provincia"],
        ["id_provincia"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("dependencia_codigo_padre_fkey"),
        "dependencia",
        "dependencia",
        ["codigo_padre"],
        ["id_dependencia"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_dependencia_conexion"),
        "dependencia",
        "conexion_database",
        ["id_conexion"],
        ["id_conexion"],
    )
    op.create_foreign_key(
        op.f("dependencia_id_municipio_fkey"),
        "dependencia",
        "municipio",
        ["id_municipio"],
        ["id_municipio"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("idx_dependencia_tipo"),
        "dependencia",
        ["id_tipo_dependencia"],
        unique=False,
    )
    op.alter_column(
        "dependencia",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "dependencia", "telefono", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    op.alter_column(
        "dependencia", "direccion", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_constraint(None, "cuenta", type_="foreignkey")
    op.create_index(
        op.f("idx_cuenta_tipo_cuenta"), "cuenta", ["id_tipo_cuenta"], unique=False
    )
    op.create_index(
        op.f("idx_cuenta_dependencia"), "cuenta", ["id_dependencia"], unique=False
    )
    op.drop_column("cuenta", "numero_cuenta")
    op.drop_column("cuenta", "id_cliente")
    op.add_column(
        "convenio",
        sa.Column("id_provedor", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "convenio", type_="foreignkey")
    op.create_foreign_key(
        op.f("convenio_id_provedor_fkey"),
        "convenio",
        "provedores",
        ["id_provedor"],
        ["id_provedores"],
    )
    op.create_index(
        op.f("idx_convenio_provedor"), "convenio", ["id_provedor"], unique=False
    )
    op.drop_column("convenio", "id_cliente")
    op.drop_column("convenio", "codigo_convenio")
    op.drop_constraint(None, "clientes", type_="foreignkey")
    op.drop_constraint(None, "clientes", type_="foreignkey")
    op.drop_constraint(None, "clientes", type_="unique")
    op.create_index(
        op.f("idx_clientes_cedula"), "clientes", ["cedula_rif"], unique=False
    )
    op.alter_column(
        "clientes",
        "fecha_registro",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "clientes", "cedula_rif", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    op.alter_column(
        "clientes",
        "nombre",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=200),
        type_=sa.VARCHAR(length=150),
        existing_nullable=False,
    )
    op.drop_column("clientes", "estado")
    op.drop_column("clientes", "tipo_relacion")
    op.drop_column("clientes", "codigo_postal")
    op.drop_column("clientes", "id_municipio")
    op.drop_column("clientes", "id_provincia")
    op.drop_column("clientes", "web")
    op.drop_column("clientes", "fax")
    op.drop_column("clientes", "tipo_persona")
    op.drop_column("clientes", "numero_cliente")
    op.add_column(
        "anexo",
        sa.Column(
            "numero_anexo", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "anexo",
        sa.Column("id_producto", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "anexo", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_anexo_producto"),
        "anexo",
        "productos",
        ["id_producto"],
        ["id_producto"],
    )
    op.create_index(op.f("idx_anexo_producto"), "anexo", ["id_producto"], unique=False)
    op.create_index(op.f("idx_anexo_numero"), "anexo", ["numero_anexo"], unique=False)
    op.create_index(
        op.f("idx_anexo_dependencia"), "anexo", ["id_dependencia"], unique=False
    )
    op.create_index(op.f("idx_anexo_convenio"), "anexo", ["id_convenio"], unique=False)
    op.alter_column(
        "anexo", "id_dependencia", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("anexo", "codigo_anexo")
    op.drop_column("anexo", "id_moneda")
    op.create_table(
        "datos_generales_dependencia",
        sa.Column(
            "id_datos_generales", sa.INTEGER(), autoincrement=True, nullable=False
        ),
        sa.Column(
            "direccion", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "telefono", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint(
            "id_datos_generales", name=op.f("datos_generales_dependencia_pkey")
        ),
    )
    op.create_table(
        "sesion",
        sa.Column("id_sesion", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("id_usuario", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("token", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column(
            "base_datos", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "fecha_login", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "fecha_expiracion",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id_usuario"], ["usuarios.id_usuario"], name=op.f("sesion_id_usuario_fkey")
        ),
        sa.PrimaryKeyConstraint("id_sesion", name=op.f("sesion_pkey")),
        sa.UniqueConstraint(
            "token",
            name=op.f("sesion_token_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "provedores",
        sa.Column("id_provedores", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "id_tipo_provedor", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "nombre_original",
            sa.VARCHAR(length=150),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "direccion_original",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "tipo_persona",
            sa.VARCHAR(length=20),
            server_default=sa.text("'JURIDICA'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "nombre_artistico",
            sa.VARCHAR(length=150),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "telefono_principal",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "telefono_secundario",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "direccion_fiscal",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("direccion_estudio", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("id_provincia", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("id_municipio", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("especialidad_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "estilo_artistico",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "tecnicas_principales",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "ano_inicio_carrera", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "estado",
            sa.VARCHAR(length=20),
            server_default=sa.text("'ACTIVO'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "fecha_registro", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "fecha_ultima_actualizacion",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "etiquetas",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "nombre",
            sa.VARCHAR(length=150),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "direccion", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["id_tipo_provedor"],
            ["tipo_provedores.id_tipo_provedores"],
            name=op.f("provedores_id_tipo_provedor_fkey"),
        ),
        sa.PrimaryKeyConstraint("id_provedores", name=op.f("provedores_pkey")),
    )
    op.create_table(
        "conexion_database",
        sa.Column("id_conexion", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "host",
            sa.VARCHAR(length=100),
            server_default=sa.text("'localhost'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "puerto",
            sa.INTEGER(),
            server_default=sa.text("5432"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "usuario", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "contrasenia", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "nombre_database",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id_conexion", name=op.f("conexion_database_pkey")),
    )
    op.create_table(
        "tipo_provedores",
        sa.Column(
            "id_tipo_provedores", sa.INTEGER(), autoincrement=True, nullable=False
        ),
        sa.Column(
            "nombre", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("descripcion", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "id_tipo_provedores", name=op.f("tipo_provedores_pkey")
        ),
    )
    op.drop_table("suplemento_producto")
    op.drop_table("factura_producto")
    op.drop_table("anexo_producto")
    op.drop_table("venta_efectivo_producto")
    op.drop_table("suplemento")
    op.drop_table("factura")
    op.drop_table("contrato_producto")
    op.drop_table("venta_efectivo")
    op.drop_table("contrato")
    op.drop_table("clientes_persona_natural")
    op.drop_table("clientes_persona_juridica")
    op.drop_table("cliente_tcp")
    op.drop_table("tipo_entidad")
    op.drop_table("tipo_cliente")
    # ### end Alembic commands ###
