"""add_clientes_ventas_detalle_ventas

Revision ID: 4afe28ed5947
Revises: 5eb4bad34494
Create Date: 2026-02-09 05:18:06.804795

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4afe28ed5947"
down_revision: Union[str, Sequence[str], None] = "5eb4bad34494"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create ENUM type first
    estadoventa_enum = sa.Enum("PENDIENTE", "COMPLETADA", "ANULADA", name="estadoventa")
    estadoventa_enum.create(op.get_bind())

    op.create_table(
        "clientes",
        sa.Column("id_cliente", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("telefono", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("cedula_rif", sa.String(length=20), nullable=True),
        sa.Column("direccion", sa.String(), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("fecha_registro", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id_cliente"),
    )
    op.create_table(
        "detalle_ventas",
        sa.Column("id_detalle", sa.Integer(), nullable=False),
        sa.Column("id_venta", sa.Integer(), nullable=False),
        sa.Column("id_producto", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("precio_unitario", sa.Numeric(scale=2), nullable=False),
        sa.Column("subtotal", sa.Numeric(scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_producto"],
            ["productos.id_producto"],
        ),
        sa.ForeignKeyConstraint(
            ["id_venta"],
            ["ventas.id_venta"],
        ),
        sa.PrimaryKeyConstraint("id_detalle"),
    )
    op.add_column(
        "productos",
        sa.Column("stock", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "ventas",
        sa.Column("id_cliente", sa.Integer(), nullable=False, server_default="1"),
    )
    op.add_column(
        "ventas",
        sa.Column(
            "fecha", sa.DateTime(), nullable=False, server_default=sa.text("NOW()")
        ),
    )
    op.add_column(
        "ventas",
        sa.Column("total", sa.Numeric(scale=2), nullable=False, server_default="0"),
    )
    op.add_column(
        "ventas",
        sa.Column(
            "estado",
            sa.Enum("PENDIENTE", "COMPLETADA", "ANULADA", name="estadoventa"),
            nullable=False,
            server_default="PENDIENTE",
        ),
    )
    op.add_column(
        "ventas", sa.Column("fecha_actualizacion", sa.DateTime(), nullable=True)
    )
    op.drop_constraint("ventas_id_transaccion_fkey", "ventas", type_="foreignkey")
    op.drop_constraint("ventas_id_producto_fkey", "ventas", type_="foreignkey")
    op.drop_constraint("ventas_id_anexo_fkey", "ventas", type_="foreignkey")
    op.drop_constraint("ventas_moneda_venta_fkey", "ventas", type_="foreignkey")
    op.drop_constraint("ventas_id_liquidacion_fkey", "ventas", type_="foreignkey")
    # Insertar cliente por defecto para las ventas existentes
    op.execute(
        "INSERT INTO clientes (nombre, activo, fecha_registro) VALUES ('Cliente General', true, NOW())"
    )
    op.create_foreign_key(
        "ventas_id_cliente_fkey", "ventas", "clientes", ["id_cliente"], ["id_cliente"]
    )
    op.drop_column("ventas", "codigo")
    op.drop_column("ventas", "id_anexo")
    op.drop_column("ventas", "id_producto")
    op.drop_column("ventas", "cantidad")
    op.drop_column("ventas", "id_liquidacion")
    op.drop_column("ventas", "moneda_venta")
    op.drop_column("ventas", "monto")
    op.drop_column("ventas", "confirmacion")
    op.drop_column("ventas", "id_transaccion")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ventas",
        sa.Column("id_transaccion", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "ventas",
        sa.Column(
            "confirmacion",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "ventas",
        sa.Column(
            "monto",
            sa.NUMERIC(precision=15, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "ventas",
        sa.Column("moneda_venta", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "ventas",
        sa.Column("id_liquidacion", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ventas",
        sa.Column("cantidad", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "ventas",
        sa.Column("id_producto", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "ventas",
        sa.Column("id_anexo", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "ventas",
        sa.Column("codigo", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.drop_constraint("ventas_id_cliente_fkey", "ventas", type_="foreignkey")
    op.create_foreign_key(
        "ventas_id_liquidacion_fkey",
        "ventas",
        "liquidacion",
        ["id_liquidacion"],
        ["id_liquidacion"],
    )
    op.create_foreign_key(
        "ventas_moneda_venta_fkey", "ventas", "moneda", ["moneda_venta"], ["id_moneda"]
    )
    op.create_foreign_key(
        "ventas_id_anexo_fkey", "ventas", "anexo", ["id_anexo"], ["id_anexo"]
    )
    op.create_foreign_key(
        "ventas_id_producto_fkey",
        "ventas",
        "productos",
        ["id_producto"],
        ["id_producto"],
    )
    op.create_foreign_key(
        "ventas_id_transaccion_fkey",
        "ventas",
        "transaccion",
        ["id_transaccion"],
        ["id_transaccion"],
    )
    op.drop_column("ventas", "fecha_actualizacion")
    op.drop_column("ventas", "estado")
    op.drop_column("ventas", "total")
    op.drop_column("ventas", "fecha")
    op.drop_column("ventas", "id_cliente")
    op.drop_column("productos", "stock")
    op.drop_table("detalle_ventas")
    op.drop_table("clientes")

    # Drop ENUM type
    estadoventa_enum = sa.Enum("PENDIENTE", "COMPLETADA", "ANULADA", name="estadoventa")
    estadoventa_enum.drop(op.get_bind())
    # ### end Alembic commands ###
