import sqlmodel

"""Add products missing fields

Revision ID: 5dd72b9a7eba
Revises: ce6966a46053
Create Date: 2026-04-07 22:13:46.793867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5dd72b9a7eba"
down_revision: Union[str, None] = "ce6966a46053"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_pago_estado"), table_name="pago")
    op.drop_index(op.f("idx_pago_factura"), table_name="pago")
    op.drop_index(op.f("idx_pago_fecha"), table_name="pago")
    op.drop_index(op.f("idx_pago_tipo"), table_name="pago")
    op.drop_table("pago")
    op.drop_table("datos_generales_dependencia")
    op.drop_index(op.f("idx_anexo_producto_producto"), table_name="anexo_producto")
    op.drop_table("anexo_producto")
    op.add_column(
        "anexo",
        sa.Column(
            "numero_anexo", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
    )
    op.add_column("anexo", sa.Column("id_producto", sa.Integer(), nullable=True))
    op.drop_index(op.f("idx_anexo_codigo"), table_name="anexo")
    op.drop_index(op.f("idx_anexo_convenio"), table_name="anexo")
    op.drop_index(op.f("idx_anexo_dependencia"), table_name="anexo")
    op.drop_constraint(op.f("anexo_id_moneda_fkey"), "anexo", type_="foreignkey")
    op.drop_constraint(op.f("anexo_id_convenio_fkey"), "anexo", type_="foreignkey")
    op.drop_constraint(op.f("anexo_id_dependencia_fkey"), "anexo", type_="foreignkey")
    op.create_foreign_key(None, "anexo", "moneda", ["id_moneda"], ["id_moneda"])
    op.create_foreign_key(None, "anexo", "convenio", ["id_convenio"], ["id_convenio"])
    op.create_foreign_key(None, "anexo", "productos", ["id_producto"], ["id_producto"])
    op.drop_column("anexo", "codigo_anexo")
    op.alter_column(
        "categorias",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "cliente_tcp",
        "direccion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        nullable=True,
    )
    op.drop_constraint(
        op.f("cliente_tcp_id_cliente_fkey"), "cliente_tcp", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "cliente_tcp", "clientes", ["id_cliente"], ["id_cliente"]
    )
    op.alter_column(
        "clientes", "tipo_persona", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    op.alter_column(
        "clientes",
        "direccion",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        nullable=True,
    )
    op.drop_constraint(op.f("clientes_numero_cliente_key"), "clientes", type_="unique")
    op.drop_index(op.f("idx_clientes_cedula"), table_name="clientes")
    op.drop_index(op.f("idx_convenio_cliente"), table_name="clientes")
    op.drop_constraint(
        op.f("clientes_id_municipio_fkey"), "clientes", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("clientes_id_provincia_fkey"), "clientes", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "clientes", "provincia", ["id_provincia"], ["id_provincia"]
    )
    op.create_foreign_key(
        None, "clientes", "municipio", ["id_municipio"], ["id_municipio"]
    )
    op.drop_constraint(
        op.f("clientes_persona_juridica_id_cliente_fkey"),
        "clientes_persona_juridica",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("clientes_persona_juridica_id_tipo_entidad_fkey"),
        "clientes_persona_juridica",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "clientes_persona_juridica",
        "tipo_entidad",
        ["id_tipo_entidad"],
        ["id_tipo_entidad"],
    )
    op.create_foreign_key(
        None, "clientes_persona_juridica", "clientes", ["id_cliente"], ["id_cliente"]
    )
    op.alter_column(
        "clientes_persona_natural",
        "direccion_trabajo",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("clientes_persona_natural_id_cliente_fkey"),
        "clientes_persona_natural",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "clientes_persona_natural", "clientes", ["id_cliente"], ["id_cliente"]
    )
    op.alter_column(
        "conexion_database",
        "host",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
        existing_server_default=sa.text("'localhost'::character varying"),
    )
    op.alter_column(
        "conexion_database",
        "puerto",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("5432"),
    )
    op.add_column(
        "contrato",
        sa.Column("codigo", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    )
    op.drop_index(op.f("idx_contrato_cliente"), table_name="contrato")
    op.drop_index(op.f("idx_contrato_estado"), table_name="contrato")
    op.drop_index(op.f("idx_contrato_moneda"), table_name="contrato")
    op.drop_index(op.f("idx_contrato_tipo"), table_name="contrato")
    op.drop_constraint(op.f("contrato_id_moneda_fkey"), "contrato", type_="foreignkey")
    op.drop_constraint(op.f("contrato_id_estado_fkey"), "contrato", type_="foreignkey")
    op.drop_constraint(
        op.f("contrato_id_tipo_contrato_fkey"), "contrato", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "contrato", "tipo_contrato", ["id_tipo_contrato"], ["id_tipo_contrato"]
    )
    op.create_foreign_key(None, "contrato", "moneda", ["id_moneda"], ["id_moneda"])
    op.create_foreign_key(
        None, "contrato", "estado_contrato", ["id_estado"], ["id_estado_contrato"]
    )
    op.add_column(
        "convenio",
        sa.Column("codigo", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    )
    op.drop_constraint(
        op.f("convenio_id_tipo_convenio_fkey"), "convenio", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "convenio", "tipo_convenio", ["id_tipo_convenio"], ["id_tipo_convenio"]
    )
    op.drop_index(op.f("idx_cuenta_cliente"), table_name="cuenta")
    op.drop_index(op.f("idx_cuenta_dependencia"), table_name="cuenta")
    op.drop_index(op.f("idx_cuenta_tipo"), table_name="cuenta")
    op.drop_constraint(op.f("cuenta_id_tipo_cuenta_fkey"), "cuenta", type_="foreignkey")
    op.drop_constraint(op.f("cuenta_id_cliente_fkey"), "cuenta", type_="foreignkey")
    op.drop_constraint(op.f("cuenta_id_moneda_fkey"), "cuenta", type_="foreignkey")
    op.drop_constraint(op.f("cuenta_id_dependencia_fkey"), "cuenta", type_="foreignkey")
    op.create_foreign_key(
        None, "cuenta", "tipo_cuenta", ["id_tipo_cuenta"], ["id_tipo_cuenta"]
    )
    op.create_foreign_key(None, "cuenta", "clientes", ["id_cliente"], ["id_cliente"])
    op.create_foreign_key(None, "cuenta", "moneda", ["id_moneda"], ["id_moneda"])
    op.create_foreign_key(
        None, "cuenta", "dependencia", ["id_dependencia"], ["id_dependencia"]
    )
    op.alter_column(
        "dependencia",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_dependencia_padre"), table_name="dependencia")
    op.drop_index(op.f("idx_dependencia_tipo"), table_name="dependencia")
    op.drop_constraint(
        op.f("dependencia_id_municipio_fkey"), "dependencia", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("dependencia_codigo_padre_fkey"), "dependencia", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("dependencia_id_tipo_dependencia_fkey"), "dependencia", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("dependencia_id_provincia_fkey"), "dependencia", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "dependencia",
        "tipo_dependencia",
        ["id_tipo_dependencia"],
        ["id_tipo_dependencia"],
    )
    op.create_foreign_key(
        None, "dependencia", "municipio", ["id_municipio"], ["id_municipio"]
    )
    op.create_foreign_key(
        None, "dependencia", "dependencia", ["codigo_padre"], ["id_dependencia"]
    )
    op.create_foreign_key(
        None, "dependencia", "provincia", ["id_provincia"], ["id_provincia"]
    )
    op.drop_index(op.f("idx_detalle_venta_producto"), table_name="detalle_ventas")
    op.drop_index(op.f("idx_detalle_venta_venta"), table_name="detalle_ventas")
    op.drop_constraint(
        op.f("detalle_ventas_id_producto_fkey"), "detalle_ventas", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("detalle_ventas_id_venta_fkey"), "detalle_ventas", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "detalle_ventas", "productos", ["id_producto"], ["id_producto"]
    )
    op.create_foreign_key(None, "detalle_ventas", "ventas", ["id_venta"], ["id_venta"])
    op.alter_column(
        "especialidades_artisticas",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "especialidades_artisticas",
        "activo",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "estado_contrato",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.add_column("factura", sa.Column("id_dependencia", sa.Integer(), nullable=True))
    op.alter_column(
        "factura",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "factura",
        "observaciones",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_factura_codigo"), table_name="factura")
    op.drop_index(op.f("idx_factura_contrato"), table_name="factura")
    op.drop_constraint(op.f("factura_id_contrato_fkey"), "factura", type_="foreignkey")
    op.create_foreign_key(
        None, "factura", "dependencia", ["id_dependencia"], ["id_dependencia"]
    )
    op.create_foreign_key(None, "factura", "contrato", ["id_contrato"], ["id_contrato"])
    op.alter_column(
        "grupo",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_item_anexo_anexo"), table_name="item_anexo")
    op.drop_index(op.f("idx_item_anexo_producto"), table_name="item_anexo")
    op.drop_constraint(
        op.f("item_anexo_id_moneda_fkey"), "item_anexo", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("item_anexo_id_anexo_fkey"), "item_anexo", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("item_anexo_id_producto_fkey"), "item_anexo", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "item_anexo", "productos", ["id_producto"], ["id_producto"]
    )
    op.create_foreign_key(None, "item_anexo", "anexo", ["id_anexo"], ["id_anexo"])
    op.create_foreign_key(None, "item_anexo", "moneda", ["id_moneda"], ["id_moneda"])
    op.drop_index(op.f("idx_item_factura_factura"), table_name="item_factura")
    op.drop_index(op.f("idx_item_factura_producto"), table_name="item_factura")
    op.drop_constraint(
        op.f("item_factura_id_factura_fkey"), "item_factura", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("item_factura_id_producto_fkey"), "item_factura", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("item_factura_id_moneda_fkey"), "item_factura", type_="foreignkey"
    )
    op.create_foreign_key(None, "item_factura", "moneda", ["id_moneda"], ["id_moneda"])
    op.create_foreign_key(
        None, "item_factura", "factura", ["id_factura"], ["id_factura"]
    )
    op.create_foreign_key(
        None, "item_factura", "productos", ["id_producto"], ["id_producto"]
    )
    op.drop_index(
        op.f("idx_item_venta_efectivo_producto"), table_name="item_venta_efectivo"
    )
    op.drop_index(
        op.f("idx_item_venta_efectivo_venta"), table_name="item_venta_efectivo"
    )
    op.drop_constraint(
        op.f("item_venta_efectivo_id_producto_fkey"),
        "item_venta_efectivo",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("item_venta_efectivo_id_moneda_fkey"),
        "item_venta_efectivo",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("item_venta_efectivo_id_venta_efectivo_fkey"),
        "item_venta_efectivo",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "item_venta_efectivo", "productos", ["id_producto"], ["id_producto"]
    )
    op.create_foreign_key(
        None,
        "item_venta_efectivo",
        "venta_efectivo",
        ["id_venta_efectivo"],
        ["id_venta_efectivo"],
    )
    op.create_foreign_key(
        None, "item_venta_efectivo", "moneda", ["id_moneda"], ["id_moneda"]
    )
    op.alter_column(
        "liquidacion",
        "liquidada",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "liquidacion",
        "observaciones",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "liquidacion",
        "devengado",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=False,
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "liquidacion",
        "tributario",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=False,
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "liquidacion",
        "comision_bancaria",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=False,
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "liquidacion",
        "gasto_empresa",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=False,
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "liquidacion",
        "importe",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=False,
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "liquidacion",
        "neto_pagar",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=False,
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "liquidacion",
        "tipo_pago",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'TRANSFERENCIA'::character varying"),
    )
    op.alter_column(
        "movimiento",
        "fecha",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "movimiento",
        "observacion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "movimiento",
        "estado",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'pendiente'::character varying"),
    )
    op.drop_index(op.f("idx_movimiento_cliente"), table_name="movimiento")
    op.drop_index(op.f("idx_movimiento_codigo"), table_name="movimiento")
    op.drop_index(op.f("idx_movimiento_convenio"), table_name="movimiento")
    op.drop_index(op.f("idx_movimiento_dependencia"), table_name="movimiento")
    op.drop_index(op.f("idx_movimiento_estado"), table_name="movimiento")
    op.drop_index(op.f("idx_movimiento_fecha"), table_name="movimiento")
    op.drop_index(op.f("idx_movimiento_id_dependencia"), table_name="movimiento")
    op.drop_index(op.f("idx_movimiento_id_producto"), table_name="movimiento")
    op.drop_index(op.f("idx_movimiento_producto"), table_name="movimiento")
    op.drop_index(op.f("idx_movimiento_tipo"), table_name="movimiento")
    op.drop_constraint(
        op.f("movimiento_id_liquidacion_fkey"), "movimiento", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movimiento_id_convenio_fkey"), "movimiento", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movimiento_id_dependencia_fkey"), "movimiento", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movimiento_moneda_venta_fkey"), "movimiento", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movimiento_id_producto_fkey"), "movimiento", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movimiento_id_cliente_fkey"), "movimiento", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movimiento_moneda_compra_fkey"), "movimiento", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movimiento_id_tipo_movimiento_fkey"), "movimiento", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movimiento_id_venta_efectivo_fkey"), "movimiento", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movimiento_id_anexo_fkey"), "movimiento", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movimiento_id_factura_fkey"), "movimiento", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movimiento_id_contrato_fkey"), "movimiento", type_="foreignkey"
    )
    op.create_foreign_key(None, "movimiento", "factura", ["id_factura"], ["id_factura"])
    op.create_foreign_key(
        None,
        "movimiento",
        "tipo_movimiento",
        ["id_tipo_movimiento"],
        ["id_tipo_movimiento"],
    )
    op.create_foreign_key(
        None, "movimiento", "convenio", ["id_convenio"], ["id_convenio"]
    )
    op.create_foreign_key(None, "movimiento", "anexo", ["id_anexo"], ["id_anexo"])
    op.create_foreign_key(
        None, "movimiento", "clientes", ["id_cliente"], ["id_cliente"]
    )
    op.create_foreign_key(
        None, "movimiento", "contrato", ["id_contrato"], ["id_contrato"]
    )
    op.create_foreign_key(
        None, "movimiento", "moneda", ["moneda_compra"], ["id_moneda"]
    )
    op.create_foreign_key(
        None, "movimiento", "liquidacion", ["id_liquidacion"], ["id_liquidacion"]
    )
    op.create_foreign_key(
        None, "movimiento", "dependencia", ["id_dependencia"], ["id_dependencia"]
    )
    op.create_foreign_key(
        None,
        "movimiento",
        "venta_efectivo",
        ["id_venta_efectivo"],
        ["id_venta_efectivo"],
    )
    op.create_foreign_key(
        None, "movimiento", "productos", ["id_producto"], ["id_producto"]
    )
    op.create_foreign_key(None, "movimiento", "moneda", ["moneda_venta"], ["id_moneda"])
    op.drop_constraint(
        op.f("municipio_id_provincia_nombre_key"), "municipio", type_="unique"
    )
    op.drop_constraint(
        op.f("municipio_id_provincia_fkey"), "municipio", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "municipio", "provincia", ["id_provincia"], ["id_provincia"]
    )
    op.add_column("productos", sa.Column("stock_minimo", sa.Integer(), nullable=True))
    op.add_column("productos", sa.Column("punto_pedido", sa.Integer(), nullable=True))
    op.add_column("productos", sa.Column("lead_time_dias", sa.Integer(), nullable=True))
    op.add_column(
        "productos",
        sa.Column(
            "clasificacion_abc",
            sqlmodel.sql.sqltypes.AutoString(length=1),
            nullable=True,
        ),
    )
    op.alter_column(
        "productos",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_productos_codigo"), table_name="productos")
    op.drop_index(op.f("idx_productos_subcategoria"), table_name="productos")
    op.drop_constraint(
        op.f("productos_id_subcategoria_fkey"), "productos", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("productos_moneda_compra_fkey"), "productos", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("productos_moneda_venta_fkey"), "productos", type_="foreignkey"
    )
    op.create_foreign_key(None, "productos", "moneda", ["moneda_compra"], ["id_moneda"])
    op.create_foreign_key(None, "productos", "moneda", ["moneda_venta"], ["id_moneda"])
    op.create_foreign_key(
        None, "productos", "subcategorias", ["id_subcategoria"], ["id_subcategoria"]
    )
    op.alter_column(
        "productos_en_liquidacion",
        "liquidada",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "productos_en_liquidacion",
        "fecha",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "sesion",
        "fecha_login",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "subcategorias",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("subcategorias_id_categoria_nombre_key"), "subcategorias", type_="unique"
    )
    op.drop_constraint(
        op.f("subcategorias_id_categoria_fkey"), "subcategorias", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "subcategorias", "categorias", ["id_categoria"], ["id_categoria"]
    )
    op.add_column(
        "suplemento",
        sa.Column("codigo", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    )
    op.drop_index(op.f("idx_suplemento_contrato"), table_name="suplemento")
    op.drop_index(op.f("idx_suplemento_estado"), table_name="suplemento")
    op.drop_constraint(
        op.f("suplemento_id_contrato_fkey"), "suplemento", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("suplemento_id_estado_fkey"), "suplemento", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "suplemento", "estado_contrato", ["id_estado"], ["id_estado_contrato"]
    )
    op.create_foreign_key(
        None, "suplemento", "contrato", ["id_contrato"], ["id_contrato"]
    )
    op.alter_column(
        "tipo_cliente",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "tipo_contrato",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "tipo_convenio",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "tipo_cuenta",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "tipo_dependencia",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "tipo_entidad",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "tipo_proveedor",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_usuarios_dependencia"), table_name="usuarios")
    op.drop_index(op.f("idx_usuarios_grupo"), table_name="usuarios")
    op.drop_constraint(op.f("usuarios_id_grupo_fkey"), "usuarios", type_="foreignkey")
    op.drop_constraint(
        op.f("usuarios_id_dependencia_fkey"), "usuarios", type_="foreignkey"
    )
    op.create_foreign_key(None, "usuarios", "grupo", ["id_grupo"], ["id_grupo"])
    op.create_foreign_key(
        None, "usuarios", "dependencia", ["id_dependencia"], ["id_dependencia"]
    )
    op.add_column(
        "venta_efectivo",
        sa.Column("codigo", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    )
    op.drop_index(op.f("idx_venta_efectivo_dependencia"), table_name="venta_efectivo")
    op.drop_index(op.f("idx_venta_efectivo_fecha"), table_name="venta_efectivo")
    op.drop_constraint(
        op.f("venta_efectivo_id_dependencia_fkey"), "venta_efectivo", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "venta_efectivo", "dependencia", ["id_dependencia"], ["id_dependencia"]
    )
    op.alter_column(
        "ventas",
        "fecha",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "ventas",
        "total",
        existing_type=sa.NUMERIC(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.execute(
        "CREATE TYPE estadoventa AS ENUM ('PENDIENTE', 'COMPLETADA', 'ANULADA');"
    )
    op.execute("ALTER TABLE ventas ALTER COLUMN estado DROP DEFAULT;")
    op.alter_column(
        "ventas",
        "estado",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("PENDIENTE", "COMPLETADA", "ANULADA", name="estadoventa"),
        postgresql_using="estado::estadoventa",
        nullable=False,
    )
    op.execute(
        "ALTER TABLE ventas ALTER COLUMN estado SET DEFAULT 'PENDIENTE'::estadoventa;"
    )
    op.alter_column(
        "ventas",
        "observacion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "ventas",
        "fecha_registro",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_index(op.f("idx_ventas_cliente"), table_name="ventas")
    op.drop_index(op.f("idx_ventas_estado"), table_name="ventas")
    op.drop_index(op.f("idx_ventas_fecha"), table_name="ventas")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_ventas_fecha"), "ventas", ["fecha"], unique=False)
    op.create_index(op.f("idx_ventas_estado"), "ventas", ["estado"], unique=False)
    op.create_index(op.f("idx_ventas_cliente"), "ventas", ["id_cliente"], unique=False)
    op.alter_column(
        "ventas",
        "fecha_registro",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "ventas",
        "observacion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "ventas",
        "estado",
        existing_type=sa.Enum("PENDIENTE", "COMPLETADA", "ANULADA", name="estadoventa"),
        type_=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'PENDIENTE'::character varying"),
    )
    op.alter_column(
        "ventas",
        "total",
        existing_type=sa.NUMERIC(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "ventas",
        "fecha",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint(None, "venta_efectivo", type_="foreignkey")
    op.create_foreign_key(
        op.f("venta_efectivo_id_dependencia_fkey"),
        "venta_efectivo",
        "dependencia",
        ["id_dependencia"],
        ["id_dependencia"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("idx_venta_efectivo_fecha"), "venta_efectivo", ["fecha"], unique=False
    )
    op.create_index(
        op.f("idx_venta_efectivo_dependencia"),
        "venta_efectivo",
        ["id_dependencia"],
        unique=False,
    )
    op.drop_column("venta_efectivo", "codigo")
    op.drop_constraint(None, "usuarios", type_="foreignkey")
    op.drop_constraint(None, "usuarios", type_="foreignkey")
    op.create_foreign_key(
        op.f("usuarios_id_dependencia_fkey"),
        "usuarios",
        "dependencia",
        ["id_dependencia"],
        ["id_dependencia"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("usuarios_id_grupo_fkey"),
        "usuarios",
        "grupo",
        ["id_grupo"],
        ["id_grupo"],
        ondelete="CASCADE",
    )
    op.create_index(op.f("idx_usuarios_grupo"), "usuarios", ["id_grupo"], unique=False)
    op.create_index(
        op.f("idx_usuarios_dependencia"), "usuarios", ["id_dependencia"], unique=False
    )
    op.alter_column(
        "tipo_proveedor",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "tipo_entidad",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "tipo_dependencia",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "tipo_cuenta",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "tipo_convenio",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "tipo_contrato",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "tipo_cliente",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "suplemento", type_="foreignkey")
    op.drop_constraint(None, "suplemento", type_="foreignkey")
    op.create_foreign_key(
        op.f("suplemento_id_estado_fkey"),
        "suplemento",
        "estado_contrato",
        ["id_estado"],
        ["id_estado_contrato"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("suplemento_id_contrato_fkey"),
        "suplemento",
        "contrato",
        ["id_contrato"],
        ["id_contrato"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("idx_suplemento_estado"), "suplemento", ["id_estado"], unique=False
    )
    op.create_index(
        op.f("idx_suplemento_contrato"), "suplemento", ["id_contrato"], unique=False
    )
    op.drop_column("suplemento", "codigo")
    op.drop_constraint(None, "subcategorias", type_="foreignkey")
    op.create_foreign_key(
        op.f("subcategorias_id_categoria_fkey"),
        "subcategorias",
        "categorias",
        ["id_categoria"],
        ["id_categoria"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        op.f("subcategorias_id_categoria_nombre_key"),
        "subcategorias",
        ["id_categoria", "nombre"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "subcategorias",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "sesion",
        "fecha_login",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "productos_en_liquidacion",
        "fecha",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "productos_en_liquidacion",
        "liquidada",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.drop_constraint(None, "productos", type_="foreignkey")
    op.drop_constraint(None, "productos", type_="foreignkey")
    op.drop_constraint(None, "productos", type_="foreignkey")
    op.create_foreign_key(
        op.f("productos_moneda_venta_fkey"),
        "productos",
        "moneda",
        ["moneda_venta"],
        ["id_moneda"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("productos_moneda_compra_fkey"),
        "productos",
        "moneda",
        ["moneda_compra"],
        ["id_moneda"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("productos_id_subcategoria_fkey"),
        "productos",
        "subcategorias",
        ["id_subcategoria"],
        ["id_subcategoria"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("idx_productos_subcategoria"),
        "productos",
        ["id_subcategoria"],
        unique=False,
    )
    op.create_index(op.f("idx_productos_codigo"), "productos", ["codigo"], unique=False)
    op.alter_column(
        "productos",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_column("productos", "clasificacion_abc")
    op.drop_column("productos", "lead_time_dias")
    op.drop_column("productos", "punto_pedido")
    op.drop_column("productos", "stock_minimo")
    op.drop_constraint(None, "municipio", type_="foreignkey")
    op.create_foreign_key(
        op.f("municipio_id_provincia_fkey"),
        "municipio",
        "provincia",
        ["id_provincia"],
        ["id_provincia"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        op.f("municipio_id_provincia_nombre_key"),
        "municipio",
        ["id_provincia", "nombre"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.create_foreign_key(
        op.f("movimiento_id_contrato_fkey"),
        "movimiento",
        "contrato",
        ["id_contrato"],
        ["id_contrato"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("movimiento_id_factura_fkey"),
        "movimiento",
        "factura",
        ["id_factura"],
        ["id_factura"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("movimiento_id_anexo_fkey"),
        "movimiento",
        "anexo",
        ["id_anexo"],
        ["id_anexo"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("movimiento_id_venta_efectivo_fkey"),
        "movimiento",
        "venta_efectivo",
        ["id_venta_efectivo"],
        ["id_venta_efectivo"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("movimiento_id_tipo_movimiento_fkey"),
        "movimiento",
        "tipo_movimiento",
        ["id_tipo_movimiento"],
        ["id_tipo_movimiento"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("movimiento_moneda_compra_fkey"),
        "movimiento",
        "moneda",
        ["moneda_compra"],
        ["id_moneda"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("movimiento_id_cliente_fkey"),
        "movimiento",
        "clientes",
        ["id_cliente"],
        ["id_cliente"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("movimiento_id_producto_fkey"),
        "movimiento",
        "productos",
        ["id_producto"],
        ["id_producto"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("movimiento_moneda_venta_fkey"),
        "movimiento",
        "moneda",
        ["moneda_venta"],
        ["id_moneda"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("movimiento_id_dependencia_fkey"),
        "movimiento",
        "dependencia",
        ["id_dependencia"],
        ["id_dependencia"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("movimiento_id_convenio_fkey"),
        "movimiento",
        "convenio",
        ["id_convenio"],
        ["id_convenio"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("movimiento_id_liquidacion_fkey"),
        "movimiento",
        "liquidacion",
        ["id_liquidacion"],
        ["id_liquidacion"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("idx_movimiento_tipo"), "movimiento", ["id_tipo_movimiento"], unique=False
    )
    op.create_index(
        op.f("idx_movimiento_producto"), "movimiento", ["id_producto"], unique=False
    )
    op.create_index(
        op.f("idx_movimiento_id_producto"), "movimiento", ["id_producto"], unique=False
    )
    op.create_index(
        op.f("idx_movimiento_id_dependencia"),
        "movimiento",
        ["id_dependencia"],
        unique=False,
    )
    op.create_index(op.f("idx_movimiento_fecha"), "movimiento", ["fecha"], unique=False)
    op.create_index(
        op.f("idx_movimiento_estado"), "movimiento", ["estado"], unique=False
    )
    op.create_index(
        op.f("idx_movimiento_dependencia"),
        "movimiento",
        ["id_dependencia"],
        unique=False,
    )
    op.create_index(
        op.f("idx_movimiento_convenio"), "movimiento", ["id_convenio"], unique=False
    )
    op.create_index(
        op.f("idx_movimiento_codigo"), "movimiento", ["codigo"], unique=False
    )
    op.create_index(
        op.f("idx_movimiento_cliente"), "movimiento", ["id_cliente"], unique=False
    )
    op.alter_column(
        "movimiento",
        "estado",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'pendiente'::character varying"),
    )
    op.alter_column(
        "movimiento",
        "observacion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "movimiento",
        "fecha",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "liquidacion",
        "tipo_pago",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'TRANSFERENCIA'::character varying"),
    )
    op.alter_column(
        "liquidacion",
        "neto_pagar",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=True,
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "liquidacion",
        "importe",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=True,
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "liquidacion",
        "gasto_empresa",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=True,
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "liquidacion",
        "comision_bancaria",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=True,
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "liquidacion",
        "tributario",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=True,
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "liquidacion",
        "devengado",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=True,
        existing_server_default=sa.text("0.00"),
    )
    op.alter_column(
        "liquidacion",
        "observaciones",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "liquidacion",
        "liquidada",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.drop_constraint(None, "item_venta_efectivo", type_="foreignkey")
    op.drop_constraint(None, "item_venta_efectivo", type_="foreignkey")
    op.drop_constraint(None, "item_venta_efectivo", type_="foreignkey")
    op.create_foreign_key(
        op.f("item_venta_efectivo_id_venta_efectivo_fkey"),
        "item_venta_efectivo",
        "venta_efectivo",
        ["id_venta_efectivo"],
        ["id_venta_efectivo"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("item_venta_efectivo_id_moneda_fkey"),
        "item_venta_efectivo",
        "moneda",
        ["id_moneda"],
        ["id_moneda"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("item_venta_efectivo_id_producto_fkey"),
        "item_venta_efectivo",
        "productos",
        ["id_producto"],
        ["id_producto"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("idx_item_venta_efectivo_venta"),
        "item_venta_efectivo",
        ["id_venta_efectivo"],
        unique=False,
    )
    op.create_index(
        op.f("idx_item_venta_efectivo_producto"),
        "item_venta_efectivo",
        ["id_producto"],
        unique=False,
    )
    op.drop_constraint(None, "item_factura", type_="foreignkey")
    op.drop_constraint(None, "item_factura", type_="foreignkey")
    op.drop_constraint(None, "item_factura", type_="foreignkey")
    op.create_foreign_key(
        op.f("item_factura_id_moneda_fkey"),
        "item_factura",
        "moneda",
        ["id_moneda"],
        ["id_moneda"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("item_factura_id_producto_fkey"),
        "item_factura",
        "productos",
        ["id_producto"],
        ["id_producto"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("item_factura_id_factura_fkey"),
        "item_factura",
        "factura",
        ["id_factura"],
        ["id_factura"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("idx_item_factura_producto"), "item_factura", ["id_producto"], unique=False
    )
    op.create_index(
        op.f("idx_item_factura_factura"), "item_factura", ["id_factura"], unique=False
    )
    op.drop_constraint(None, "item_anexo", type_="foreignkey")
    op.drop_constraint(None, "item_anexo", type_="foreignkey")
    op.drop_constraint(None, "item_anexo", type_="foreignkey")
    op.create_foreign_key(
        op.f("item_anexo_id_producto_fkey"),
        "item_anexo",
        "productos",
        ["id_producto"],
        ["id_producto"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("item_anexo_id_anexo_fkey"),
        "item_anexo",
        "anexo",
        ["id_anexo"],
        ["id_anexo"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("item_anexo_id_moneda_fkey"),
        "item_anexo",
        "moneda",
        ["id_moneda"],
        ["id_moneda"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("idx_item_anexo_producto"), "item_anexo", ["id_producto"], unique=False
    )
    op.create_index(
        op.f("idx_item_anexo_anexo"), "item_anexo", ["id_anexo"], unique=False
    )
    op.alter_column(
        "grupo",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "factura", type_="foreignkey")
    op.drop_constraint(None, "factura", type_="foreignkey")
    op.create_foreign_key(
        op.f("factura_id_contrato_fkey"),
        "factura",
        "contrato",
        ["id_contrato"],
        ["id_contrato"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("idx_factura_contrato"), "factura", ["id_contrato"], unique=False
    )
    op.create_index(
        op.f("idx_factura_codigo"), "factura", ["codigo_factura"], unique=False
    )
    op.alter_column(
        "factura",
        "observaciones",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "factura",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_column("factura", "id_dependencia")
    op.alter_column(
        "estado_contrato",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "especialidades_artisticas",
        "activo",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "especialidades_artisticas",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "detalle_ventas", type_="foreignkey")
    op.drop_constraint(None, "detalle_ventas", type_="foreignkey")
    op.create_foreign_key(
        op.f("detalle_ventas_id_venta_fkey"),
        "detalle_ventas",
        "ventas",
        ["id_venta"],
        ["id_venta"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("detalle_ventas_id_producto_fkey"),
        "detalle_ventas",
        "productos",
        ["id_producto"],
        ["id_producto"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("idx_detalle_venta_venta"), "detalle_ventas", ["id_venta"], unique=False
    )
    op.create_index(
        op.f("idx_detalle_venta_producto"),
        "detalle_ventas",
        ["id_producto"],
        unique=False,
    )
    op.drop_constraint(None, "dependencia", type_="foreignkey")
    op.drop_constraint(None, "dependencia", type_="foreignkey")
    op.drop_constraint(None, "dependencia", type_="foreignkey")
    op.drop_constraint(None, "dependencia", type_="foreignkey")
    op.create_foreign_key(
        op.f("dependencia_id_provincia_fkey"),
        "dependencia",
        "provincia",
        ["id_provincia"],
        ["id_provincia"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("dependencia_id_tipo_dependencia_fkey"),
        "dependencia",
        "tipo_dependencia",
        ["id_tipo_dependencia"],
        ["id_tipo_dependencia"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("dependencia_codigo_padre_fkey"),
        "dependencia",
        "dependencia",
        ["codigo_padre"],
        ["id_dependencia"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("dependencia_id_municipio_fkey"),
        "dependencia",
        "municipio",
        ["id_municipio"],
        ["id_municipio"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("idx_dependencia_tipo"),
        "dependencia",
        ["id_tipo_dependencia"],
        unique=False,
    )
    op.create_index(
        op.f("idx_dependencia_padre"), "dependencia", ["codigo_padre"], unique=False
    )
    op.alter_column(
        "dependencia",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "cuenta", type_="foreignkey")
    op.drop_constraint(None, "cuenta", type_="foreignkey")
    op.drop_constraint(None, "cuenta", type_="foreignkey")
    op.drop_constraint(None, "cuenta", type_="foreignkey")
    op.create_foreign_key(
        op.f("cuenta_id_dependencia_fkey"),
        "cuenta",
        "dependencia",
        ["id_dependencia"],
        ["id_dependencia"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("cuenta_id_moneda_fkey"),
        "cuenta",
        "moneda",
        ["id_moneda"],
        ["id_moneda"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("cuenta_id_cliente_fkey"),
        "cuenta",
        "clientes",
        ["id_cliente"],
        ["id_cliente"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("cuenta_id_tipo_cuenta_fkey"),
        "cuenta",
        "tipo_cuenta",
        ["id_tipo_cuenta"],
        ["id_tipo_cuenta"],
        ondelete="SET NULL",
    )
    op.create_index(op.f("idx_cuenta_tipo"), "cuenta", ["id_tipo_cuenta"], unique=False)
    op.create_index(
        op.f("idx_cuenta_dependencia"), "cuenta", ["id_dependencia"], unique=False
    )
    op.create_index(op.f("idx_cuenta_cliente"), "cuenta", ["id_cliente"], unique=False)
    op.drop_constraint(None, "convenio", type_="foreignkey")
    op.create_foreign_key(
        op.f("convenio_id_tipo_convenio_fkey"),
        "convenio",
        "tipo_convenio",
        ["id_tipo_convenio"],
        ["id_tipo_convenio"],
        ondelete="CASCADE",
    )
    op.drop_column("convenio", "codigo")
    op.drop_constraint(None, "contrato", type_="foreignkey")
    op.drop_constraint(None, "contrato", type_="foreignkey")
    op.drop_constraint(None, "contrato", type_="foreignkey")
    op.create_foreign_key(
        op.f("contrato_id_tipo_contrato_fkey"),
        "contrato",
        "tipo_contrato",
        ["id_tipo_contrato"],
        ["id_tipo_contrato"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("contrato_id_estado_fkey"),
        "contrato",
        "estado_contrato",
        ["id_estado"],
        ["id_estado_contrato"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("contrato_id_moneda_fkey"),
        "contrato",
        "moneda",
        ["id_moneda"],
        ["id_moneda"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("idx_contrato_tipo"), "contrato", ["id_tipo_contrato"], unique=False
    )
    op.create_index(
        op.f("idx_contrato_moneda"), "contrato", ["id_moneda"], unique=False
    )
    op.create_index(
        op.f("idx_contrato_estado"), "contrato", ["id_estado"], unique=False
    )
    op.create_index(
        op.f("idx_contrato_cliente"), "contrato", ["id_cliente"], unique=False
    )
    op.drop_column("contrato", "codigo")
    op.alter_column(
        "conexion_database",
        "puerto",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("5432"),
    )
    op.alter_column(
        "conexion_database",
        "host",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
        existing_server_default=sa.text("'localhost'::character varying"),
    )
    op.drop_constraint(None, "clientes_persona_natural", type_="foreignkey")
    op.create_foreign_key(
        op.f("clientes_persona_natural_id_cliente_fkey"),
        "clientes_persona_natural",
        "clientes",
        ["id_cliente"],
        ["id_cliente"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "clientes_persona_natural",
        "direccion_trabajo",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "clientes_persona_juridica", type_="foreignkey")
    op.drop_constraint(None, "clientes_persona_juridica", type_="foreignkey")
    op.create_foreign_key(
        op.f("clientes_persona_juridica_id_tipo_entidad_fkey"),
        "clientes_persona_juridica",
        "tipo_entidad",
        ["id_tipo_entidad"],
        ["id_tipo_entidad"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("clientes_persona_juridica_id_cliente_fkey"),
        "clientes_persona_juridica",
        "clientes",
        ["id_cliente"],
        ["id_cliente"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "clientes", type_="foreignkey")
    op.drop_constraint(None, "clientes", type_="foreignkey")
    op.create_foreign_key(
        op.f("clientes_id_provincia_fkey"),
        "clientes",
        "provincia",
        ["id_provincia"],
        ["id_provincia"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("clientes_id_municipio_fkey"),
        "clientes",
        "municipio",
        ["id_municipio"],
        ["id_municipio"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("idx_convenio_cliente"), "clientes", ["id_cliente"], unique=False
    )
    op.create_index(
        op.f("idx_clientes_cedula"), "clientes", ["cedula_rif"], unique=False
    )
    op.create_unique_constraint(
        op.f("clientes_numero_cliente_key"),
        "clientes",
        ["numero_cliente"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "clientes",
        "direccion",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "clientes", "tipo_persona", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.drop_constraint(None, "cliente_tcp", type_="foreignkey")
    op.create_foreign_key(
        op.f("cliente_tcp_id_cliente_fkey"),
        "cliente_tcp",
        "clientes",
        ["id_cliente"],
        ["id_cliente"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "cliente_tcp",
        "direccion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "categorias",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.add_column(
        "anexo",
        sa.Column(
            "codigo_anexo", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "anexo", type_="foreignkey")
    op.drop_constraint(None, "anexo", type_="foreignkey")
    op.drop_constraint(None, "anexo", type_="foreignkey")
    op.create_foreign_key(
        op.f("anexo_id_dependencia_fkey"),
        "anexo",
        "dependencia",
        ["id_dependencia"],
        ["id_dependencia"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("anexo_id_convenio_fkey"),
        "anexo",
        "convenio",
        ["id_convenio"],
        ["id_convenio"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("anexo_id_moneda_fkey"),
        "anexo",
        "moneda",
        ["id_moneda"],
        ["id_moneda"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("idx_anexo_dependencia"), "anexo", ["id_dependencia"], unique=False
    )
    op.create_index(op.f("idx_anexo_convenio"), "anexo", ["id_convenio"], unique=False)
    op.create_index(op.f("idx_anexo_codigo"), "anexo", ["codigo_anexo"], unique=False)
    op.drop_column("anexo", "id_producto")
    op.drop_column("anexo", "numero_anexo")
    op.create_table(
        "anexo_producto",
        sa.Column(
            "id_anexo_producto", sa.INTEGER(), autoincrement=True, nullable=False
        ),
        sa.Column("id_anexo", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id_producto", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "cantidad",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "precio_acordado",
            sa.NUMERIC(precision=15, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id_anexo"],
            ["anexo.id_anexo"],
            name=op.f("anexo_producto_id_anexo_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["id_producto"],
            ["productos.id_producto"],
            name=op.f("anexo_producto_id_producto_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id_anexo_producto", name=op.f("anexo_producto_pkey")),
        sa.UniqueConstraint(
            "id_anexo",
            "id_producto",
            name=op.f("anexo_producto_id_anexo_id_producto_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_anexo_producto_producto"),
        "anexo_producto",
        ["id_producto"],
        unique=False,
    )
    op.create_table(
        "datos_generales_dependencia",
        sa.Column(
            "id_datos_generales", sa.INTEGER(), autoincrement=True, nullable=False
        ),
        sa.Column(
            "direccion", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "telefono", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint(
            "id_datos_generales", name=op.f("datos_generales_dependencia_pkey")
        ),
    )
    op.create_table(
        "pago",
        sa.Column("id_pago", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("id_factura", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id_moneda", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "monto",
            sa.NUMERIC(precision=15, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "tipo_pago", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "estado",
            sa.VARCHAR(length=20),
            server_default=sa.text("'COMPLETADO'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "fecha_pago",
            sa.DATE(),
            server_default=sa.text("CURRENT_DATE"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "fecha_registro",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "referencia_pago",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("observaciones", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("id_usuario", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.CheckConstraint(
            "estado::text = ANY (ARRAY['PENDIENTE'::character varying, 'COMPLETADO'::character varying, 'ANULADO'::character varying]::text[])",
            name=op.f("pago_estado_check"),
        ),
        sa.CheckConstraint(
            "tipo_pago::text = ANY (ARRAY['EFECTIVO'::character varying, 'TRANSFERENCIA'::character varying, 'CHEQUE'::character varying, 'TARJETA'::character varying, 'OTRO'::character varying]::text[])",
            name=op.f("pago_tipo_pago_check"),
        ),
        sa.ForeignKeyConstraint(
            ["id_factura"],
            ["factura.id_factura"],
            name=op.f("pago_id_factura_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["id_moneda"],
            ["moneda.id_moneda"],
            name=op.f("pago_id_moneda_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["id_usuario"],
            ["usuarios.id_usuario"],
            name=op.f("pago_id_usuario_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id_pago", name=op.f("pago_pkey")),
    )
    op.create_index(op.f("idx_pago_tipo"), "pago", ["tipo_pago"], unique=False)
    op.create_index(op.f("idx_pago_fecha"), "pago", ["fecha_pago"], unique=False)
    op.create_index(op.f("idx_pago_factura"), "pago", ["id_factura"], unique=False)
    op.create_index(op.f("idx_pago_estado"), "pago", ["estado"], unique=False)
    # ### end Alembic commands ###
