"""Initial migration

Revision ID: 5eb4bad34494
Revises: 
Create Date: 2026-02-04 21:29:38.156586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5eb4bad34494"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "categorias",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("dependencia_id_datos_generales_fkey"), "dependencia", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("dependencia_id_tipo_dependencia_fkey"), "dependencia", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "dependencia",
        "datos_generales_dependencia",
        ["id_datos_generales"],
        ["id_datos_generales"],
    )
    op.create_foreign_key(
        None,
        "dependencia",
        "tipo_dependencia",
        ["id_tipo_dependencia"],
        ["id_tipo_dependencia"],
    )
    op.alter_column(
        "movimiento",
        "observacion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("movimiento_id_producto_fkey"), "movimiento", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movimiento_id_liquidacion_fkey"), "movimiento", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movimiento_id_tipo_movimiento_fkey"), "movimiento", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movimiento_id_dependencia_fkey"), "movimiento", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movimiento_id_anexo_fkey"), "movimiento", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "movimiento", "liquidacion", ["id_liquidacion"], ["id_liquidacion"]
    )
    op.create_foreign_key(
        None, "movimiento", "dependencia", ["id_dependencia"], ["id_dependencia"]
    )
    op.create_foreign_key(None, "movimiento", "anexo", ["id_anexo"], ["id_anexo"])
    op.create_foreign_key(
        None,
        "movimiento",
        "tipo_movimiento",
        ["id_tipo_movimiento"],
        ["id_tipo_movimiento"],
    )
    op.create_foreign_key(
        None, "movimiento", "productos", ["id_producto"], ["id_producto"]
    )
    op.alter_column(
        "productos",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("productos_id_subcategoria_fkey"), "productos", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("productos_moneda_compra_fkey"), "productos", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("productos_moneda_venta_fkey"), "productos", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "productos", "subcategorias", ["id_subcategoria"], ["id_subcategoria"]
    )
    op.create_foreign_key(None, "productos", "moneda", ["moneda_compra"], ["id_moneda"])
    op.create_foreign_key(None, "productos", "moneda", ["moneda_venta"], ["id_moneda"])
    op.alter_column(
        "subcategorias",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("subcategorias_id_categoria_nombre_key"), "subcategorias", type_="unique"
    )
    op.drop_constraint(
        op.f("subcategorias_id_categoria_fkey"), "subcategorias", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "subcategorias", "categorias", ["id_categoria"], ["id_categoria"]
    )
    op.alter_column(
        "tipo_dependencia",
        "descripcion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "ventas",
        "observacion",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "ventas",
        "fecha_registro",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint(op.f("ventas_id_producto_fkey"), "ventas", type_="foreignkey")
    op.drop_constraint(op.f("ventas_moneda_venta_fkey"), "ventas", type_="foreignkey")
    op.drop_constraint(op.f("ventas_id_transaccion_fkey"), "ventas", type_="foreignkey")
    op.drop_constraint(op.f("ventas_id_liquidacion_fkey"), "ventas", type_="foreignkey")
    op.drop_constraint(op.f("ventas_id_anexo_fkey"), "ventas", type_="foreignkey")
    op.create_foreign_key(
        None, "ventas", "transaccion", ["id_transaccion"], ["id_transaccion"]
    )
    op.create_foreign_key(None, "ventas", "productos", ["id_producto"], ["id_producto"])
    op.create_foreign_key(None, "ventas", "anexo", ["id_anexo"], ["id_anexo"])
    op.create_foreign_key(
        None, "ventas", "liquidacion", ["id_liquidacion"], ["id_liquidacion"]
    )
    op.create_foreign_key(None, "ventas", "moneda", ["moneda_venta"], ["id_moneda"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ventas", type_="foreignkey")
    op.drop_constraint(None, "ventas", type_="foreignkey")
    op.drop_constraint(None, "ventas", type_="foreignkey")
    op.drop_constraint(None, "ventas", type_="foreignkey")
    op.drop_constraint(None, "ventas", type_="foreignkey")
    op.create_foreign_key(
        op.f("ventas_id_anexo_fkey"),
        "ventas",
        "anexo",
        ["id_anexo"],
        ["id_anexo"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("ventas_id_liquidacion_fkey"),
        "ventas",
        "liquidacion",
        ["id_liquidacion"],
        ["id_liquidacion"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("ventas_id_transaccion_fkey"),
        "ventas",
        "transaccion",
        ["id_transaccion"],
        ["id_transaccion"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("ventas_moneda_venta_fkey"),
        "ventas",
        "moneda",
        ["moneda_venta"],
        ["id_moneda"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("ventas_id_producto_fkey"),
        "ventas",
        "productos",
        ["id_producto"],
        ["id_producto"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "ventas",
        "fecha_registro",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "ventas",
        "observacion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "tipo_dependencia",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "subcategorias", type_="foreignkey")
    op.create_foreign_key(
        op.f("subcategorias_id_categoria_fkey"),
        "subcategorias",
        "categorias",
        ["id_categoria"],
        ["id_categoria"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        op.f("subcategorias_id_categoria_nombre_key"),
        "subcategorias",
        ["id_categoria", "nombre"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "subcategorias",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "productos", type_="foreignkey")
    op.drop_constraint(None, "productos", type_="foreignkey")
    op.drop_constraint(None, "productos", type_="foreignkey")
    op.create_foreign_key(
        op.f("productos_moneda_venta_fkey"),
        "productos",
        "moneda",
        ["moneda_venta"],
        ["id_moneda"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("productos_moneda_compra_fkey"),
        "productos",
        "moneda",
        ["moneda_compra"],
        ["id_moneda"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("productos_id_subcategoria_fkey"),
        "productos",
        "subcategorias",
        ["id_subcategoria"],
        ["id_subcategoria"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "productos",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.drop_constraint(None, "movimiento", type_="foreignkey")
    op.create_foreign_key(
        op.f("movimiento_id_anexo_fkey"),
        "movimiento",
        "anexo",
        ["id_anexo"],
        ["id_anexo"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("movimiento_id_dependencia_fkey"),
        "movimiento",
        "dependencia",
        ["id_dependencia"],
        ["id_dependencia"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("movimiento_id_tipo_movimiento_fkey"),
        "movimiento",
        "tipo_movimiento",
        ["id_tipo_movimiento"],
        ["id_tipo_movimiento"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("movimiento_id_liquidacion_fkey"),
        "movimiento",
        "liquidacion",
        ["id_liquidacion"],
        ["id_liquidacion"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("movimiento_id_producto_fkey"),
        "movimiento",
        "productos",
        ["id_producto"],
        ["id_producto"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "movimiento",
        "observacion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "dependencia", type_="foreignkey")
    op.drop_constraint(None, "dependencia", type_="foreignkey")
    op.create_foreign_key(
        op.f("dependencia_id_tipo_dependencia_fkey"),
        "dependencia",
        "tipo_dependencia",
        ["id_tipo_dependencia"],
        ["id_tipo_dependencia"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("dependencia_id_datos_generales_fkey"),
        "dependencia",
        "datos_generales_dependencia",
        ["id_datos_generales"],
        ["id_datos_generales"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "categorias",
        "descripcion",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
