"""sync_db_to_models

Revision ID: 883157d23e47
Revises: seed_generic_data
Create Date: 2026-08-26 12:06:50.183592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '883157d23e47'
down_revision: Union[str, None] = 'seed_generic_data'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anexo_producto')
    op.drop_constraint(op.f('anexo_id_convenio_fkey'), 'anexo', type_='foreignkey')
    op.create_foreign_key(None, 'anexo', 'dependencia', ['id_dependencia'], ['id_dependencia'])
    op.create_foreign_key(None, 'anexo', 'convenio', ['id_convenio'], ['id_convenio'])
    op.alter_column('categorias', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('certificacion', 'constructor',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('certificacion', 'inversionista',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('certificacion', 'obra',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('certificacion', 'objeto_obra',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('certificacion', 'actividad',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('certificacion', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('certificacion', 'observaciones',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('certificacion', 'a_cobrar',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('certificacion', 'impuesto_venta_onat',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('certificacion', 'ajuste_porciento',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('certificacion', 'ajuste_valor',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('certificacion', 'facturado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('cliente_tcp', 'direccion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)
    op.drop_constraint(op.f('cliente_tcp_id_cliente_fkey'), 'cliente_tcp', type_='foreignkey')
    op.create_foreign_key(None, 'cliente_tcp', 'clientes', ['id_cliente'], ['id_cliente'])
    op.alter_column('clientes', 'tipo_persona',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('clientes', 'direccion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.drop_constraint(op.f('clientes_id_provincia_fkey'), 'clientes', type_='foreignkey')
    op.drop_constraint(op.f('clientes_id_municipio_fkey'), 'clientes', type_='foreignkey')
    op.create_foreign_key(None, 'clientes', 'municipio', ['id_municipio'], ['id_municipio'])
    op.create_foreign_key(None, 'clientes', 'provincia', ['id_provincia'], ['id_provincia'])
    op.drop_column('clientes', 'activo')
    op.drop_constraint(op.f('clientes_persona_juridica_id_cliente_fkey'), 'clientes_persona_juridica', type_='foreignkey')
    op.drop_constraint(op.f('clientes_persona_juridica_id_tipo_entidad_fkey'), 'clientes_persona_juridica', type_='foreignkey')
    op.create_foreign_key(None, 'clientes_persona_juridica', 'clientes', ['id_cliente'], ['id_cliente'])
    op.create_foreign_key(None, 'clientes_persona_juridica', 'tipo_entidad', ['id_tipo_entidad'], ['id_tipo_entidad'])
    op.alter_column('clientes_persona_natural', 'direccion_trabajo',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('clientes_persona_natural_id_cliente_fkey'), 'clientes_persona_natural', type_='foreignkey')
    op.create_foreign_key(None, 'clientes_persona_natural', 'clientes', ['id_cliente'], ['id_cliente'])
    op.alter_column('compras', 'fecha',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('compras', 'observacion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('compras', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('compras', 'fecha_actualizacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('conexion_database', 'host',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'localhost'::character varying"))
    op.alter_column('conexion_database', 'puerto',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5432'))
    op.drop_constraint(op.f('contrato_id_tipo_contrato_fkey'), 'contrato', type_='foreignkey')
    op.drop_constraint(op.f('contrato_id_estado_fkey'), 'contrato', type_='foreignkey')
    op.drop_constraint(op.f('contrato_id_moneda_fkey'), 'contrato', type_='foreignkey')
    op.create_foreign_key(None, 'contrato', 'tipo_contrato', ['id_tipo_contrato'], ['id_tipo_contrato'])
    op.create_foreign_key(None, 'contrato', 'estado_contrato', ['id_estado'], ['id_estado_contrato'])
    op.create_foreign_key(None, 'contrato', 'moneda', ['id_moneda'], ['id_moneda'])
    op.drop_constraint(op.f('convenio_id_tipo_convenio_fkey'), 'convenio', type_='foreignkey')
    op.create_foreign_key(None, 'convenio', 'tipo_convenio', ['id_tipo_convenio'], ['id_tipo_convenio'])
    op.drop_constraint(op.f('cuenta_id_cliente_fkey'), 'cuenta', type_='foreignkey')
    op.drop_constraint(op.f('cuenta_id_dependencia_fkey'), 'cuenta', type_='foreignkey')
    op.drop_constraint(op.f('cuenta_id_moneda_fkey'), 'cuenta', type_='foreignkey')
    op.create_foreign_key(None, 'cuenta', 'clientes', ['id_cliente'], ['id_cliente'])
    op.create_foreign_key(None, 'cuenta', 'dependencia', ['id_dependencia'], ['id_dependencia'])
    op.create_foreign_key(None, 'cuenta', 'moneda', ['id_moneda'], ['id_moneda'])
    op.drop_constraint(op.f('cuenta_dependencias_id_dependencia_fkey'), 'cuenta_dependencias', type_='foreignkey')
    op.drop_constraint(op.f('cuenta_dependencias_id_moneda_fkey'), 'cuenta_dependencias', type_='foreignkey')
    op.create_foreign_key(None, 'cuenta_dependencias', 'dependencia', ['id_dependencia'], ['id_dependencia'])
    op.create_foreign_key(None, 'cuenta_dependencias', 'moneda', ['id_moneda'], ['id_moneda'])
    op.drop_column('cuenta_dependencias', 'tipo_cuenta')
    op.alter_column('dependencia', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('dependencia_id_tipo_dependencia_fkey'), 'dependencia', type_='foreignkey')
    op.drop_constraint(op.f('dependencia_codigo_padre_fkey'), 'dependencia', type_='foreignkey')
    op.drop_constraint(op.f('dependencia_id_municipio_fkey'), 'dependencia', type_='foreignkey')
    op.drop_constraint(op.f('dependencia_id_provincia_fkey'), 'dependencia', type_='foreignkey')
    op.create_foreign_key(None, 'dependencia', 'dependencia', ['codigo_padre'], ['id_dependencia'])
    op.create_foreign_key(None, 'dependencia', 'provincia', ['id_provincia'], ['id_provincia'])
    op.create_foreign_key(None, 'dependencia', 'tipo_dependencia', ['id_tipo_dependencia'], ['id_tipo_dependencia'])
    op.create_foreign_key(None, 'dependencia', 'municipio', ['id_municipio'], ['id_municipio'])
    op.drop_constraint(op.f('detalle_compras_id_producto_fkey'), 'detalle_compras', type_='foreignkey')
    op.drop_constraint(op.f('detalle_compras_id_compra_fkey'), 'detalle_compras', type_='foreignkey')
    op.create_foreign_key(None, 'detalle_compras', 'productos', ['id_producto'], ['id_producto'])
    op.create_foreign_key(None, 'detalle_compras', 'compras', ['id_compra'], ['id_compra'])
    op.drop_constraint(op.f('detalle_ventas_id_venta_fkey'), 'detalle_ventas', type_='foreignkey')
    op.drop_constraint(op.f('detalle_ventas_id_producto_fkey'), 'detalle_ventas', type_='foreignkey')
    op.create_foreign_key(None, 'detalle_ventas', 'productos', ['id_producto'], ['id_producto'])
    op.create_foreign_key(None, 'detalle_ventas', 'ventas', ['id_venta'], ['id_venta'])
    op.alter_column('especialidades_artisticas', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('especialidades_artisticas', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('estado_contrato', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('etapas', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('etapas', 'valor',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('etapas', 'pagada',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('factura', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('factura', 'observaciones',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('factura_id_contrato_fkey'), 'factura', type_='foreignkey')
    op.drop_constraint(op.f('fk_factura_cuenta'), 'factura', type_='foreignkey')
    op.create_foreign_key(None, 'factura', 'contrato', ['id_contrato'], ['id_contrato'])
    op.drop_column('factura', 'id_cuenta')
    op.alter_column('factura_servicio', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('factura_servicio', 'importe',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('factura_servicio', 'pagado',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('factura_servicio', 'observaciones',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_foreign_key(None, 'factura_servicio', 'usuarios', ['id_usuario'], ['id_usuario'])
    op.alter_column('grupo', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('item_anexo', 'vendido',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('item_anexo_id_anexo_fkey'), 'item_anexo', type_='foreignkey')
    op.drop_constraint(op.f('item_anexo_id_producto_fkey'), 'item_anexo', type_='foreignkey')
    op.drop_constraint(op.f('item_anexo_id_moneda_fkey'), 'item_anexo', type_='foreignkey')
    op.create_foreign_key(None, 'item_anexo', 'moneda', ['id_moneda'], ['id_moneda'])
    op.create_foreign_key(None, 'item_anexo', 'productos', ['id_producto'], ['id_producto'])
    op.create_foreign_key(None, 'item_anexo', 'anexo', ['id_anexo'], ['id_anexo'])
    op.drop_constraint(op.f('item_factura_id_moneda_fkey'), 'item_factura', type_='foreignkey')
    op.drop_constraint(op.f('item_factura_id_factura_fkey'), 'item_factura', type_='foreignkey')
    op.drop_constraint(op.f('item_factura_id_producto_fkey'), 'item_factura', type_='foreignkey')
    op.create_foreign_key(None, 'item_factura', 'factura', ['id_factura'], ['id_factura'])
    op.create_foreign_key(None, 'item_factura', 'moneda', ['id_moneda'], ['id_moneda'])
    op.create_foreign_key(None, 'item_factura', 'productos', ['id_producto'], ['id_producto'])
    op.drop_constraint(op.f('item_venta_efectivo_id_producto_fkey'), 'item_venta_efectivo', type_='foreignkey')
    op.drop_constraint(op.f('item_venta_efectivo_id_venta_efectivo_fkey'), 'item_venta_efectivo', type_='foreignkey')
    op.drop_constraint(op.f('item_venta_efectivo_id_moneda_fkey'), 'item_venta_efectivo', type_='foreignkey')
    op.create_foreign_key(None, 'item_venta_efectivo', 'venta_efectivo', ['id_venta_efectivo'], ['id_venta_efectivo'])
    op.create_foreign_key(None, 'item_venta_efectivo', 'productos', ['id_producto'], ['id_producto'])
    op.create_foreign_key(None, 'item_venta_efectivo', 'moneda', ['id_moneda'], ['id_moneda'])
    op.alter_column('items_factura_servicio', 'concepto',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('items_factura_servicio', 'cantidad',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('items_factura_servicio', 'precio',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('items_factura_servicio', 'ajuste_porciento',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('items_factura_servicio', 'ajuste_valor',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('items_oferta', 'concepto',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('liquidacion', 'liquidada',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('liquidacion', 'observaciones',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('liquidacion', 'devengado',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('liquidacion', 'tributario',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('liquidacion', 'comision_bancaria',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('liquidacion', 'gasto_empresa',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('liquidacion', 'importe',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('liquidacion', 'neto_pagar',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('liquidacion', 'porcentaje_caguayo',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('10.00'))
    op.alter_column('liquidacion', 'importe_caguayo',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('liquidacion', 'tributario_monto',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('liquidacion', 'tipo_pago',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'TRANSFERENCIA'::character varying"))
    # Clean up invalid usuario_id=0 references before adding FK
    op.execute("UPDATE log SET usuario_id = NULL WHERE usuario_id = 0")
    op.create_foreign_key(None, 'log', 'usuarios', ['usuario_id'], ['id_usuario'])
    op.alter_column('movimiento', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('movimiento', 'observacion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('movimiento', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pendiente'::character varying"))
    op.drop_constraint(op.f('movimiento_id_convenio_fkey'), 'movimiento', type_='foreignkey')
    op.drop_constraint(op.f('movimiento_id_liquidacion_fkey'), 'movimiento', type_='foreignkey')
    op.drop_constraint(op.f('movimiento_moneda_compra_fkey'), 'movimiento', type_='foreignkey')
    op.drop_constraint(op.f('movimiento_moneda_venta_fkey'), 'movimiento', type_='foreignkey')
    op.drop_constraint(op.f('movimiento_id_contrato_fkey'), 'movimiento', type_='foreignkey')
    op.drop_constraint(op.f('movimiento_id_tipo_movimiento_fkey'), 'movimiento', type_='foreignkey')
    op.drop_constraint(op.f('movimiento_id_factura_fkey'), 'movimiento', type_='foreignkey')
    op.drop_constraint(op.f('movimiento_id_producto_fkey'), 'movimiento', type_='foreignkey')
    op.drop_constraint(op.f('movimiento_id_venta_efectivo_fkey'), 'movimiento', type_='foreignkey')
    op.drop_constraint(op.f('movimiento_id_anexo_fkey'), 'movimiento', type_='foreignkey')
    op.drop_constraint(op.f('movimiento_id_cliente_fkey'), 'movimiento', type_='foreignkey')
    op.create_foreign_key(None, 'movimiento', 'venta_efectivo', ['id_venta_efectivo'], ['id_venta_efectivo'])
    op.create_foreign_key(None, 'movimiento', 'liquidacion', ['id_liquidacion'], ['id_liquidacion'])
    op.create_foreign_key(None, 'movimiento', 'factura', ['id_factura'], ['id_factura'])
    op.create_foreign_key(None, 'movimiento', 'moneda', ['moneda_compra'], ['id_moneda'])
    op.create_foreign_key(None, 'movimiento', 'contrato', ['id_contrato'], ['id_contrato'])
    op.create_foreign_key(None, 'movimiento', 'clientes', ['id_cliente'], ['id_cliente'])
    op.create_foreign_key(None, 'movimiento', 'tipo_movimiento', ['id_tipo_movimiento'], ['id_tipo_movimiento'])
    op.create_foreign_key(None, 'movimiento', 'anexo', ['id_anexo'], ['id_anexo'])
    op.create_foreign_key(None, 'movimiento', 'convenio', ['id_convenio'], ['id_convenio'])
    op.create_foreign_key(None, 'movimiento', 'productos', ['id_producto'], ['id_producto'])
    op.create_foreign_key(None, 'movimiento', 'moneda', ['moneda_venta'], ['id_moneda'])
    op.drop_constraint(op.f('municipio_id_provincia_fkey'), 'municipio', type_='foreignkey')
    op.create_foreign_key(None, 'municipio', 'provincia', ['id_provincia'], ['id_provincia'])
    op.alter_column('oferta', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('oferta', 'observaciones',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('pago', 'observaciones',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('pago_factura_servicio', 'monto',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('pago_factura_servicio', 'monto_disponible',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_etapa', 'cobro',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_etapa', 'liquidada',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('persona_etapa', 'por_cobrar',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'fecha_emision',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('persona_liquidacion', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('persona_liquidacion', 'tipo_pago',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'TRANSFERENCIA'::character varying"))
    op.alter_column('persona_liquidacion', 'importe',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'porcentaje_caguayo',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('10.00'))
    op.alter_column('persona_liquidacion', 'importe_caguayo',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'porciento_gestion',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'porciento_empresa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'devengado',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'tributario',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'tributario_monto',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'comision_bancaria',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'neto_pagar',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'gasto_empresa',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'observacion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('persona_liquidacion', 'confirmado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('productos', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('productos_moneda_venta_fkey'), 'productos', type_='foreignkey')
    op.drop_constraint(op.f('productos_id_subcategoria_fkey'), 'productos', type_='foreignkey')
    op.drop_constraint(op.f('productos_moneda_compra_fkey'), 'productos', type_='foreignkey')
    op.create_foreign_key(None, 'productos', 'subcategorias', ['id_subcategoria'], ['id_subcategoria'])
    op.create_foreign_key(None, 'productos', 'moneda', ['moneda_compra'], ['id_moneda'])
    op.create_foreign_key(None, 'productos', 'moneda', ['moneda_venta'], ['id_moneda'])
    op.alter_column('productos_en_liquidacion', 'liquidada',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('productos_en_liquidacion', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('servicios', 'concepto',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('servicios', 'precio',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('servicios', 'observaciones',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('sesion', 'fecha_login',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('solicitud_servicio', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('solicitud_servicio', 'fecha_solicitud',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('solicitud_servicio', 'observaciones',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('solicitud_servicio', 'material_asumido_x',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('solicitud_servicio', 'aprobado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_foreign_key(None, 'solicitud_servicio', 'usuarios', ['id_usuario'], ['id_usuario'])
    op.alter_column('subcategorias', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('subcategorias_id_categoria_fkey'), 'subcategorias', type_='foreignkey')
    op.create_foreign_key(None, 'subcategorias', 'categorias', ['id_categoria'], ['id_categoria'])
    op.drop_constraint(op.f('suplemento_id_estado_fkey'), 'suplemento', type_='foreignkey')
    op.drop_constraint(op.f('suplemento_id_contrato_fkey'), 'suplemento', type_='foreignkey')
    op.create_foreign_key(None, 'suplemento', 'estado_contrato', ['id_estado'], ['id_estado_contrato'])
    op.create_foreign_key(None, 'suplemento', 'contrato', ['id_contrato'], ['id_contrato'])
    op.alter_column('tareas_etapa', 'concepto_modificado',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('tareas_etapa', 'cantidad',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('tareas_etapa', 'precio_ajustado',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('tareas_etapa', 'observaciones_ajustadas',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('tipo_cliente', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('tipo_contrato', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('tipo_convenio', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('tipo_dependencia', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('tipo_entidad', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('tipo_proveedor', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('usuarios_id_dependencia_fkey'), 'usuarios', type_='foreignkey')
    op.drop_constraint(op.f('usuarios_id_grupo_fkey'), 'usuarios', type_='foreignkey')
    op.create_foreign_key(None, 'usuarios', 'dependencia', ['id_dependencia'], ['id_dependencia'])
    op.create_foreign_key(None, 'usuarios', 'grupo', ['id_grupo'], ['id_grupo'])
    op.create_foreign_key(None, 'venta_efectivo', 'dependencia', ['id_dependencia'], ['id_dependencia'])
    op.alter_column('ventas', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ventas', 'total',
               existing_type=sa.NUMERIC(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ventas', 'estado',
               existing_type=postgresql.ENUM('PENDIENTE', 'COMPLETADA', 'ANULADA', name='estadoventa'),
               nullable=False,
               existing_server_default=sa.text("'PENDIENTE'::estadoventa"))
    op.alter_column('ventas', 'observacion',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('ventas', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ventas', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ventas', 'observacion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ventas', 'estado',
               existing_type=postgresql.ENUM('PENDIENTE', 'COMPLETADA', 'ANULADA', name='estadoventa'),
               nullable=True,
               existing_server_default=sa.text("'PENDIENTE'::estadoventa"))
    op.alter_column('ventas', 'total',
               existing_type=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ventas', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'venta_efectivo', type_='foreignkey')
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.create_foreign_key(op.f('usuarios_id_grupo_fkey'), 'usuarios', 'grupo', ['id_grupo'], ['id_grupo'], ondelete='CASCADE')
    op.create_foreign_key(op.f('usuarios_id_dependencia_fkey'), 'usuarios', 'dependencia', ['id_dependencia'], ['id_dependencia'], ondelete='SET NULL')
    op.alter_column('tipo_proveedor', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tipo_entidad', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tipo_dependencia', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tipo_convenio', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tipo_contrato', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tipo_cliente', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tareas_etapa', 'observaciones_ajustadas',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tareas_etapa', 'precio_ajustado',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('tareas_etapa', 'cantidad',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('tareas_etapa', 'concepto_modificado',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'suplemento', type_='foreignkey')
    op.drop_constraint(None, 'suplemento', type_='foreignkey')
    op.create_foreign_key(op.f('suplemento_id_contrato_fkey'), 'suplemento', 'contrato', ['id_contrato'], ['id_contrato'], ondelete='CASCADE')
    op.create_foreign_key(op.f('suplemento_id_estado_fkey'), 'suplemento', 'estado_contrato', ['id_estado'], ['id_estado_contrato'], ondelete='CASCADE')
    op.drop_constraint(None, 'subcategorias', type_='foreignkey')
    op.create_foreign_key(op.f('subcategorias_id_categoria_fkey'), 'subcategorias', 'categorias', ['id_categoria'], ['id_categoria'], ondelete='CASCADE')
    op.alter_column('subcategorias', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'solicitud_servicio', type_='foreignkey')
    op.alter_column('solicitud_servicio', 'aprobado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('solicitud_servicio', 'material_asumido_x',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('solicitud_servicio', 'observaciones',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('solicitud_servicio', 'fecha_solicitud',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('solicitud_servicio', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sesion', 'fecha_login',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('servicios', 'observaciones',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('servicios', 'precio',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('servicios', 'concepto',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('productos_en_liquidacion', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('productos_en_liquidacion', 'liquidada',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.create_foreign_key(op.f('productos_moneda_compra_fkey'), 'productos', 'moneda', ['moneda_compra'], ['id_moneda'], ondelete='CASCADE')
    op.create_foreign_key(op.f('productos_id_subcategoria_fkey'), 'productos', 'subcategorias', ['id_subcategoria'], ['id_subcategoria'], ondelete='CASCADE')
    op.create_foreign_key(op.f('productos_moneda_venta_fkey'), 'productos', 'moneda', ['moneda_venta'], ['id_moneda'], ondelete='CASCADE')
    op.alter_column('productos', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('persona_liquidacion', 'confirmado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('persona_liquidacion', 'observacion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('persona_liquidacion', 'gasto_empresa',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'neto_pagar',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'comision_bancaria',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'tributario_monto',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'tributario',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'devengado',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'porciento_empresa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'porciento_gestion',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'importe_caguayo',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'porcentaje_caguayo',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('10.00'))
    op.alter_column('persona_liquidacion', 'importe',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_liquidacion', 'tipo_pago',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'TRANSFERENCIA'::character varying"))
    op.alter_column('persona_liquidacion', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('persona_liquidacion', 'fecha_emision',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('persona_etapa', 'por_cobrar',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('persona_etapa', 'liquidada',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('persona_etapa', 'cobro',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('pago_factura_servicio', 'monto_disponible',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('pago_factura_servicio', 'monto',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('pago', 'observaciones',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('oferta', 'observaciones',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('oferta', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'municipio', type_='foreignkey')
    op.create_foreign_key(op.f('municipio_id_provincia_fkey'), 'municipio', 'provincia', ['id_provincia'], ['id_provincia'], ondelete='CASCADE')
    op.drop_constraint(None, 'movimiento', type_='foreignkey')
    op.drop_constraint(None, 'movimiento', type_='foreignkey')
    op.drop_constraint(None, 'movimiento', type_='foreignkey')
    op.drop_constraint(None, 'movimiento', type_='foreignkey')
    op.drop_constraint(None, 'movimiento', type_='foreignkey')
    op.drop_constraint(None, 'movimiento', type_='foreignkey')
    op.drop_constraint(None, 'movimiento', type_='foreignkey')
    op.drop_constraint(None, 'movimiento', type_='foreignkey')
    op.drop_constraint(None, 'movimiento', type_='foreignkey')
    op.drop_constraint(None, 'movimiento', type_='foreignkey')
    op.drop_constraint(None, 'movimiento', type_='foreignkey')
    op.create_foreign_key(op.f('movimiento_id_cliente_fkey'), 'movimiento', 'clientes', ['id_cliente'], ['id_cliente'], ondelete='SET NULL')
    op.create_foreign_key(op.f('movimiento_id_anexo_fkey'), 'movimiento', 'anexo', ['id_anexo'], ['id_anexo'], ondelete='CASCADE')
    op.create_foreign_key(op.f('movimiento_id_venta_efectivo_fkey'), 'movimiento', 'venta_efectivo', ['id_venta_efectivo'], ['id_venta_efectivo'], ondelete='CASCADE')
    op.create_foreign_key(op.f('movimiento_id_producto_fkey'), 'movimiento', 'productos', ['id_producto'], ['id_producto'], ondelete='CASCADE')
    op.create_foreign_key(op.f('movimiento_id_factura_fkey'), 'movimiento', 'factura', ['id_factura'], ['id_factura'], ondelete='CASCADE')
    op.create_foreign_key(op.f('movimiento_id_tipo_movimiento_fkey'), 'movimiento', 'tipo_movimiento', ['id_tipo_movimiento'], ['id_tipo_movimiento'], ondelete='CASCADE')
    op.create_foreign_key(op.f('movimiento_id_contrato_fkey'), 'movimiento', 'contrato', ['id_contrato'], ['id_contrato'], ondelete='CASCADE')
    op.create_foreign_key(op.f('movimiento_moneda_venta_fkey'), 'movimiento', 'moneda', ['moneda_venta'], ['id_moneda'], ondelete='CASCADE')
    op.create_foreign_key(op.f('movimiento_moneda_compra_fkey'), 'movimiento', 'moneda', ['moneda_compra'], ['id_moneda'], ondelete='CASCADE')
    op.create_foreign_key(op.f('movimiento_id_liquidacion_fkey'), 'movimiento', 'liquidacion', ['id_liquidacion'], ['id_liquidacion'], ondelete='CASCADE')
    op.create_foreign_key(op.f('movimiento_id_convenio_fkey'), 'movimiento', 'convenio', ['id_convenio'], ['id_convenio'], ondelete='CASCADE')
    op.alter_column('movimiento', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pendiente'::character varying"))
    op.alter_column('movimiento', 'observacion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('movimiento', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.alter_column('liquidacion', 'tipo_pago',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'TRANSFERENCIA'::character varying"))
    op.alter_column('liquidacion', 'tributario_monto',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('liquidacion', 'importe_caguayo',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('liquidacion', 'porcentaje_caguayo',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('10.00'))
    op.alter_column('liquidacion', 'neto_pagar',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('liquidacion', 'importe',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('liquidacion', 'gasto_empresa',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('liquidacion', 'comision_bancaria',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('liquidacion', 'tributario',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('liquidacion', 'devengado',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('liquidacion', 'observaciones',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('liquidacion', 'liquidada',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('items_oferta', 'concepto',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('items_factura_servicio', 'ajuste_valor',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('items_factura_servicio', 'ajuste_porciento',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('items_factura_servicio', 'precio',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('items_factura_servicio', 'cantidad',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('items_factura_servicio', 'concepto',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'item_venta_efectivo', type_='foreignkey')
    op.drop_constraint(None, 'item_venta_efectivo', type_='foreignkey')
    op.drop_constraint(None, 'item_venta_efectivo', type_='foreignkey')
    op.create_foreign_key(op.f('item_venta_efectivo_id_moneda_fkey'), 'item_venta_efectivo', 'moneda', ['id_moneda'], ['id_moneda'], ondelete='CASCADE')
    op.create_foreign_key(op.f('item_venta_efectivo_id_venta_efectivo_fkey'), 'item_venta_efectivo', 'venta_efectivo', ['id_venta_efectivo'], ['id_venta_efectivo'], ondelete='CASCADE')
    op.create_foreign_key(op.f('item_venta_efectivo_id_producto_fkey'), 'item_venta_efectivo', 'productos', ['id_producto'], ['id_producto'], ondelete='CASCADE')
    op.drop_constraint(None, 'item_factura', type_='foreignkey')
    op.drop_constraint(None, 'item_factura', type_='foreignkey')
    op.drop_constraint(None, 'item_factura', type_='foreignkey')
    op.create_foreign_key(op.f('item_factura_id_producto_fkey'), 'item_factura', 'productos', ['id_producto'], ['id_producto'], ondelete='CASCADE')
    op.create_foreign_key(op.f('item_factura_id_factura_fkey'), 'item_factura', 'factura', ['id_factura'], ['id_factura'], ondelete='CASCADE')
    op.create_foreign_key(op.f('item_factura_id_moneda_fkey'), 'item_factura', 'moneda', ['id_moneda'], ['id_moneda'], ondelete='CASCADE')
    op.drop_constraint(None, 'item_anexo', type_='foreignkey')
    op.drop_constraint(None, 'item_anexo', type_='foreignkey')
    op.drop_constraint(None, 'item_anexo', type_='foreignkey')
    op.create_foreign_key(op.f('item_anexo_id_moneda_fkey'), 'item_anexo', 'moneda', ['id_moneda'], ['id_moneda'], ondelete='CASCADE')
    op.create_foreign_key(op.f('item_anexo_id_producto_fkey'), 'item_anexo', 'productos', ['id_producto'], ['id_producto'], ondelete='CASCADE')
    op.create_foreign_key(op.f('item_anexo_id_anexo_fkey'), 'item_anexo', 'anexo', ['id_anexo'], ['id_anexo'], ondelete='CASCADE')
    op.alter_column('item_anexo', 'vendido',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('grupo', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'factura_servicio', type_='foreignkey')
    op.alter_column('factura_servicio', 'observaciones',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('factura_servicio', 'pagado',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('factura_servicio', 'importe',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('factura_servicio', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('factura', sa.Column('id_cuenta', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'factura', type_='foreignkey')
    op.create_foreign_key(op.f('fk_factura_cuenta'), 'factura', 'cuenta', ['id_cuenta'], ['id_cuenta'])
    op.create_foreign_key(op.f('factura_id_contrato_fkey'), 'factura', 'contrato', ['id_contrato'], ['id_contrato'], ondelete='CASCADE')
    op.alter_column('factura', 'observaciones',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('factura', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('etapas', 'pagada',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('etapas', 'valor',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('etapas', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('estado_contrato', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('especialidades_artisticas', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('especialidades_artisticas', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'detalle_ventas', type_='foreignkey')
    op.drop_constraint(None, 'detalle_ventas', type_='foreignkey')
    op.create_foreign_key(op.f('detalle_ventas_id_producto_fkey'), 'detalle_ventas', 'productos', ['id_producto'], ['id_producto'], ondelete='CASCADE')
    op.create_foreign_key(op.f('detalle_ventas_id_venta_fkey'), 'detalle_ventas', 'ventas', ['id_venta'], ['id_venta'], ondelete='CASCADE')
    op.drop_constraint(None, 'detalle_compras', type_='foreignkey')
    op.drop_constraint(None, 'detalle_compras', type_='foreignkey')
    op.create_foreign_key(op.f('detalle_compras_id_compra_fkey'), 'detalle_compras', 'compras', ['id_compra'], ['id_compra'], ondelete='CASCADE')
    op.create_foreign_key(op.f('detalle_compras_id_producto_fkey'), 'detalle_compras', 'productos', ['id_producto'], ['id_producto'], ondelete='CASCADE')
    op.drop_constraint(None, 'dependencia', type_='foreignkey')
    op.drop_constraint(None, 'dependencia', type_='foreignkey')
    op.drop_constraint(None, 'dependencia', type_='foreignkey')
    op.drop_constraint(None, 'dependencia', type_='foreignkey')
    op.create_foreign_key(op.f('dependencia_id_provincia_fkey'), 'dependencia', 'provincia', ['id_provincia'], ['id_provincia'], ondelete='SET NULL')
    op.create_foreign_key(op.f('dependencia_id_municipio_fkey'), 'dependencia', 'municipio', ['id_municipio'], ['id_municipio'], ondelete='SET NULL')
    op.create_foreign_key(op.f('dependencia_codigo_padre_fkey'), 'dependencia', 'dependencia', ['codigo_padre'], ['id_dependencia'], ondelete='SET NULL')
    op.create_foreign_key(op.f('dependencia_id_tipo_dependencia_fkey'), 'dependencia', 'tipo_dependencia', ['id_tipo_dependencia'], ['id_tipo_dependencia'], ondelete='CASCADE')
    op.alter_column('dependencia', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('cuenta_dependencias', sa.Column('tipo_cuenta', sa.VARCHAR(length=50), server_default=sa.text("'CUP'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cuenta_dependencias', type_='foreignkey')
    op.drop_constraint(None, 'cuenta_dependencias', type_='foreignkey')
    op.create_foreign_key(op.f('cuenta_dependencias_id_moneda_fkey'), 'cuenta_dependencias', 'moneda', ['id_moneda'], ['id_moneda'], ondelete='SET NULL')
    op.create_foreign_key(op.f('cuenta_dependencias_id_dependencia_fkey'), 'cuenta_dependencias', 'dependencia', ['id_dependencia'], ['id_dependencia'], ondelete='CASCADE')
    op.drop_constraint(None, 'cuenta', type_='foreignkey')
    op.drop_constraint(None, 'cuenta', type_='foreignkey')
    op.drop_constraint(None, 'cuenta', type_='foreignkey')
    op.create_foreign_key(op.f('cuenta_id_moneda_fkey'), 'cuenta', 'moneda', ['id_moneda'], ['id_moneda'], ondelete='SET NULL')
    op.create_foreign_key(op.f('cuenta_id_dependencia_fkey'), 'cuenta', 'dependencia', ['id_dependencia'], ['id_dependencia'], ondelete='SET NULL')
    op.create_foreign_key(op.f('cuenta_id_cliente_fkey'), 'cuenta', 'clientes', ['id_cliente'], ['id_cliente'], ondelete='CASCADE')
    op.drop_constraint(None, 'convenio', type_='foreignkey')
    op.create_foreign_key(op.f('convenio_id_tipo_convenio_fkey'), 'convenio', 'tipo_convenio', ['id_tipo_convenio'], ['id_tipo_convenio'], ondelete='CASCADE')
    op.drop_constraint(None, 'contrato', type_='foreignkey')
    op.drop_constraint(None, 'contrato', type_='foreignkey')
    op.drop_constraint(None, 'contrato', type_='foreignkey')
    op.create_foreign_key(op.f('contrato_id_moneda_fkey'), 'contrato', 'moneda', ['id_moneda'], ['id_moneda'], ondelete='CASCADE')
    op.create_foreign_key(op.f('contrato_id_estado_fkey'), 'contrato', 'estado_contrato', ['id_estado'], ['id_estado_contrato'], ondelete='CASCADE')
    op.create_foreign_key(op.f('contrato_id_tipo_contrato_fkey'), 'contrato', 'tipo_contrato', ['id_tipo_contrato'], ['id_tipo_contrato'], ondelete='CASCADE')
    op.alter_column('conexion_database', 'puerto',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5432'))
    op.alter_column('conexion_database', 'host',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'localhost'::character varying"))
    op.alter_column('compras', 'fecha_actualizacion',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('compras', 'fecha_registro',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('compras', 'observacion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('compras', 'fecha',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'clientes_persona_natural', type_='foreignkey')
    op.create_foreign_key(op.f('clientes_persona_natural_id_cliente_fkey'), 'clientes_persona_natural', 'clientes', ['id_cliente'], ['id_cliente'], ondelete='CASCADE')
    op.alter_column('clientes_persona_natural', 'direccion_trabajo',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'clientes_persona_juridica', type_='foreignkey')
    op.drop_constraint(None, 'clientes_persona_juridica', type_='foreignkey')
    op.create_foreign_key(op.f('clientes_persona_juridica_id_tipo_entidad_fkey'), 'clientes_persona_juridica', 'tipo_entidad', ['id_tipo_entidad'], ['id_tipo_entidad'], ondelete='SET NULL')
    op.create_foreign_key(op.f('clientes_persona_juridica_id_cliente_fkey'), 'clientes_persona_juridica', 'clientes', ['id_cliente'], ['id_cliente'], ondelete='CASCADE')
    op.add_column('clientes', sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.create_foreign_key(op.f('clientes_id_municipio_fkey'), 'clientes', 'municipio', ['id_municipio'], ['id_municipio'], ondelete='SET NULL')
    op.create_foreign_key(op.f('clientes_id_provincia_fkey'), 'clientes', 'provincia', ['id_provincia'], ['id_provincia'], ondelete='SET NULL')
    op.alter_column('clientes', 'direccion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('clientes', 'tipo_persona',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(None, 'cliente_tcp', type_='foreignkey')
    op.create_foreign_key(op.f('cliente_tcp_id_cliente_fkey'), 'cliente_tcp', 'clientes', ['id_cliente'], ['id_cliente'], ondelete='CASCADE')
    op.alter_column('cliente_tcp', 'direccion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('certificacion', 'facturado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('certificacion', 'ajuste_valor',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('certificacion', 'ajuste_porciento',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('certificacion', 'impuesto_venta_onat',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('certificacion', 'a_cobrar',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('certificacion', 'observaciones',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('certificacion', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('certificacion', 'actividad',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('certificacion', 'objeto_obra',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('certificacion', 'obra',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('certificacion', 'inversionista',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('certificacion', 'constructor',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('categorias', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'anexo', type_='foreignkey')
    op.drop_constraint(None, 'anexo', type_='foreignkey')
    op.create_foreign_key(op.f('anexo_id_convenio_fkey'), 'anexo', 'convenio', ['id_convenio'], ['id_convenio'], ondelete='CASCADE')
    op.create_table('anexo_producto',
    sa.Column('id_anexo_producto', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_anexo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_producto', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_acordado', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_anexo'], ['anexo.id_anexo'], name=op.f('anexo_producto_id_anexo_fkey')),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name=op.f('anexo_producto_id_producto_fkey')),
    sa.PrimaryKeyConstraint('id_anexo_producto', name=op.f('anexo_producto_pkey'))
    )
    # ### end Alembic commands ###
