"""add contrasenia_plana to usuarios

Revision ID: c1e6f9a2348c
Revises: 883157d23e47
Create Date: 2026-08-27 12:06:13.369629

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e6f9a2348c'
down_revision: Union[str, None] = '883157d23e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('contrasenia_plana', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'contrasenia_plana')
    # ### end Alembic commands ###
