"""add_ventas_clientes_data

Revision ID: d29e26c4e3a2
Revises: 4afe28ed5947
Create Date: 2026-02-09 15:30:45.293419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29e26c4e3a2'
down_revision: Union[str, Sequence[str], None] = '4afe28ed5947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
